(function(){
    var modules={
        "panel-main-local-sleep":    			{url:"$H/p/panel-main.html",router:1},
        "panel-child-local-sleep":    			{url:"$H/p/panel-child.html"},
        "panel-export-screening":   {url:"$H/m/export/panel-export-screening.html",router:1},
        "panel-export-baseline":    {url:"$H/m/export/panel-export-baseline.html",router:1},
        "panel-export-treatment1":    {url:"$H/m/export/panel-export-treatment1.html",router:1},
        "panel-export-treatment2":    {url:"$H/m/export/panel-export-treatment2.html",router:1},
        "panel-export-6month":    {url:"$H/m/export/panel-export-6month.html",router:1},
        "panel-export-followup":    {url:"$H/m/export/panel-export-followup.html",router:1},
        "export-data": {url:"$H/m/export/export-data.html",Table:"local-sleep-export",form_module:"export-form"},
        "export-form": {url:"$H/m/export/export-form.html",Table:"local-sleep-export"},
        
        "participant-data":   		{url:"$H/m/participant/participant-data.html",Table:"local-sleep-participant",form_module:"participant-form",router:1,
                                            child_panel:"panel-child-local-sleep",
                                            questionnaire_setup:"online-questionnaire-setup-local-sleep",
                                            online_questionnaire:"online-questionnaire-app-local-sleep",
                                            participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                            participant_export:"ID,Randomisation_Number,Subject_ID,Screening_Number,Subject_Initials,Gender,DOB"
                                        },
        "participant-form":   		{url:"$H/m/participant/participant-form.html",Table:"local-sleep-participant"},

        "online-questionnaire-setup-local-sleep": 	{url:"$H/online-questionnaire/m/setup.html",Table:"local-sleep-participant"},
        "online-questionnaire-app-local-sleep":    {url:"$H/online-questionnaire/index.html"},

        "notes":  		  	  			{url:" $H/m/library/notes.html"},
        "notes-data":  	    {url:" $H/m/library/notes-data.html",Table:"local-sleep-notes",form_module:"notes-form",router:1},
        "notes-form":  	    {url:" $H/m/library/notes-form.html",Table:"local-sleep-notes"},


        "local-sleep-randomisation-table-data":		    {url:" $H/m/library/randomisation-table-data.html",Table:"local-sleep-randomisation-table",form_module:"local-sleep-randomisation-table-form"},
        "local-sleep-randomisation-table-form":		    {url:" $H/m/library/randomisation-table-form.html",Table:"local-sleep-randomisation-table"},
        "local-sleep-g-adverse-event-data":                {url:" $H/m/library/adverse-event-data.html",Table:"local-sleep-g-adverse-event",form_module:"local-sleep-g-adverse-event-form",task_name:"General - Adverse Event"},
        "local-sleep-g-adverse-event-form":                {url:" $H/m/library/adverse-event-form.html",Table:"local-sleep-g-adverse-event"},
        "local-sleep-g-file-notes-data":                {url:" $H/m/library/file-notes-data.html",Table:"local-sleep-g-file-notes",form_module:"local-sleep-g-file-notes-form",task_name:"General - File Notes"},
        "local-sleep-g-file-notes-form":                {url:" $H/m/library/file-notes-form.html",Table:"local-sleep-g-file-notes",task_name:"General - File Notes"},
        "local-sleep-g-protocol-amendments-data":                {url:" $H/m/library/protocol-amendments-data.html",Table:"local-sleep-g-protocol-amendments",form_module:"local-sleep-g-protocol-amendments-form"},
        "local-sleep-g-protocol-amendments-form":                {url:" $H/m/library/protocol-amendments-form.html",Table:"local-sleep-g-protocol-amendments"},

        "local-sleep-s-date-data":		                    {url:" $H/m/library/date-data.html",Table:"local-sleep-s-date",form_module:"local-sleep-s-date-form",task_name:"Screening - Visit Date"},
        "local-sleep-s-date-form":		                    {url:" $H/m/library/date-form.html",Table:"local-sleep-s-date"},
        "local-sleep-s-consent-data":		                    {url:" $H/m/library/consent-data.html",Table:"local-sleep-s-consent",form_module:"local-sleep-s-consent-form",task_name:"Screening - Digital consent form"},
        "local-sleep-s-consent-form":		                    {url:" $H/m/library/consent-form.html",Table:"local-sleep-s-consent",task_name:"Digital consent form"},
        "local-sleep-b-d1-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-b-d1-date",form_module:"local-sleep-b-d1-date-form",task_name:"Baseline Day 1 - Visit Date"},
        "local-sleep-b-d1-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-b-d1-date"},
        "local-sleep-b-d2-date-data":		            {url:" $H/m/library/date-data.html",Table:"local-sleep-b-d2-date",form_module:"local-sleep-b-d2-date-form",task_name:"Baseline Day 2 - Visit Date"},
        "local-sleep-b-d2-date-form":		            {url:" $H/m/library/date-form.html",Table:"local-sleep-b-d2-date"},
        "local-sleep-b-d3-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-b-d3-date",form_module:"local-sleep-b-d3-date-form",task_name:"Baseline Day 3 - Visit Date"},
        "local-sleep-b-d3-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-b-d3-date"},
        "local-sleep-t1-d1-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t1-d1-date",form_module:"local-sleep-t1-d1-date-form",task_name:"Treatment 1 Day 1 - Visit Date"},
        "local-sleep-t1-d1-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t1-d1-date"},
        "local-sleep-t1-d2-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t1-d2-date",form_module:"local-sleep-t1-d2-date-form",task_name:"Treatment 1 Day 2 - Visit Date"},
        "local-sleep-t1-d2-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t1-d2-date"},
        "local-sleep-t1-d3-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t1-d3-date",form_module:"local-sleep-t1-d3-date-form",task_name:"Treatment 1 Day 3 - Visit Date"},
        "local-sleep-t1-d3-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t1-d3-date"},
        "local-sleep-t1-d4-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t1-d4-date",form_module:"local-sleep-t1-d4-date-form",task_name:"Treatment 1 Day 2 - Visit Date"},
        "local-sleep-t1-d4-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t1-d4-date"},
        "local-sleep-t1-d5-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t1-d5-date",form_module:"local-sleep-t1-d5-date-form",task_name:"Treatment 1 Day 3 - Visit Date"},
        "local-sleep-t1-d5-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t1-d5-date"},
        "local-sleep-t2-d1-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t2-d1-date",form_module:"local-sleep-t2-d1-date-form",task_name:"Treatment 2 Day 1 - Visit Date"},
        "local-sleep-t2-d1-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t2-d1-date"},
        "local-sleep-t2-d2-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t2-d2-date",form_module:"local-sleep-t2-d2-date-form",task_name:"Treatment 2 Day 2 - Visit Date"},
        "local-sleep-t2-d2-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t2-d2-date"},
        "local-sleep-t2-d3-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t2-d3-date",form_module:"local-sleep-t2-d3-date-form",task_name:"Treatment 2 Day 3 - Visit Date"},
        "local-sleep-t2-d3-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t2-d3-date"},
        "local-sleep-t2-d4-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t2-d4-date",form_module:"local-sleep-t2-d4-date-form",task_name:"Treatment 2 Day 2 - Visit Date"},
        "local-sleep-t2-d4-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t2-d4-date"},
        "local-sleep-t2-d5-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-t2-d5-date",form_module:"local-sleep-t2-d5-date-form",task_name:"Treatment 2 Day 3 - Visit Date"},
        "local-sleep-t2-d5-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-t2-d5-date"},

        "local-sleep-6m-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-6m-date",form_module:"local-sleep-6m-date-form",task_name:"6 Months - Visit Date"},
        "local-sleep-6m-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-6m-date"},
        "local-sleep-6m-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-6m-cpap-upload",form_module:"local-sleep-6m-cpap-upload-form",task_name:"6 Months - CPAP Upload"},
        "local-sleep-6m-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-6m-cpap-upload"},
        "local-sleep-6m-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-6m-cpap",form_module:"local-sleep-6m-cpap-form",task_name:"6 Months - CPAP"},
        "local-sleep-6m-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-6m-cpap"},

        "local-sleep-fu-d1-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-fu-d1-date",form_module:"local-sleep-fu-d1-date-form",task_name:"Follow up Day 1 - Visit Date"},
        "local-sleep-fu-d1-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-fu-d1-date"},
        "local-sleep-fu-d2-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-fu-d2-date",form_module:"local-sleep-fu-d2-date-form",task_name:"Follow up Day 2 - Visit Date"},
        "local-sleep-fu-d2-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-fu-d2-date"},
        "local-sleep-fu-d3-date-data":		                {url:" $H/m/library/date-data.html",Table:"local-sleep-fu-d3-date",form_module:"local-sleep-fu-d3-date-form",task_name:"Follow up Day 3 - Visit Date"},
        "local-sleep-fu-d3-date-form":		                {url:" $H/m/library/date-form.html",Table:"local-sleep-fu-d3-date"},

        "local-sleep-s-inclusion-exclusion-data":           {url:" $H/m/library/inclusion-exclusion-data.html",Table:"local-sleep-s-inclusion-exclusion",form_module:"local-sleep-s-inclusion-exclusion-form",task_name:"Screening - Inclusion/Exclusion Criteria"},
        "local-sleep-s-inclusion-exclusion-form":           {url:" $H/m/library/inclusion-exclusion-form.html",Table:"local-sleep-s-inclusion-exclusion",task_name:"Inclusion/Exclusion Criteria"},
        "local-sleep-s-concom-file-data":		                    {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-s-concom-file",form_module:"local-sleep-s-concom-file-form",task_name:"Screening - Concomitant medication file upload"},
        "local-sleep-s-concom-file-form":		                    {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-s-concom-file"},
        "local-sleep-s-medications-data":		                        {url:" $H/m/library/medications-data.html",Table:"local-sleep-s-medications",form_module:"local-sleep-s-medications-form",task_name:"Screening - Concomitant medication"},
        "local-sleep-s-medications-form":		                {url:" $H/m/library/medications-form.html",Table:"local-sleep-s-medications",task_name:"Concomitant medication"},
        "local-sleep-s-medical-history-data":		                        {url:" $H/m/library/medical-history-data.html",Table:"local-sleep-s-medical-history",form_module:"local-sleep-s-medical-history-form",task_name:"Screening - Medical history"},
        "local-sleep-s-medical-history-form":		                {url:" $H/m/library/medical-history-form.html",Table:"local-sleep-s-medical-history",task_name:"Medical history"},
        "local-sleep-s-ess-data":		                        {url:" $H/m/library/ess-data.html",Table:"local-sleep-s-ess",form_module:"local-sleep-s-ess-form",task_name:"Screening - ESS"},
        "local-sleep-s-ess-form":		                {url:" $H/m/library/ess-screening-form.html",Table:"local-sleep-s-ess",task_name:"ESS"},
        "local-sleep-s-cpap-withdrawal-data":		                        {url:" $H/m/library/cpap-withdrawal-data.html",Table:"local-sleep-s-cpap-withdrawal",form_module:"local-sleep-s-cpap-withdrawal-form",task_name:"Screening - CPAP Withdrawal"},
        "local-sleep-s-cpap-withdrawal-form":		                {url:" $H/m/library/cpap-withdrawal-form.html",Table:"local-sleep-s-cpap-withdrawal",task_name:"CPAP Withdrawal"},
        "local-sleep-s-mva-data":		                        {url:" $H/m/library/mva-data.html",Table:"local-sleep-s-mva",form_module:"local-sleep-s-mva-form",task_name:"Screening - Motor Vehicle Accident Questionnaire"},
        "local-sleep-s-mva-form":		                {url:" $H/m/library/mva-form.html",Table:"local-sleep-s-mva",task_name:"MVA"},
        "local-sleep-s-aused-30-data":		                        {url:" $H/m/library/aused30-data.html",Table:"local-sleep-s-aused-30",form_module:"local-sleep-s-aused-30-form",task_name:"Screening - Aused 30 mins"},
        "local-sleep-s-aused-30-form":		                {url:" $H/m/library/aused30-form.html",Table:"local-sleep-s-aused-30",task_name:"Screening - Aused 30 mins"},
        "local-sleep-s-anthropometry-data":		                        {url:" $H/m/library/anthropometry-data.html",Table:"local-sleep-s-anthropometry",form_module:"local-sleep-s-anthropometry-form",task_name:"Screening - Anthropomentry"},
        "local-sleep-s-anthropometry-form":		                {url:" $H/m/library/anthropometry-form.html",Table:"local-sleep-s-anthropometry"},
        "local-sleep-s-n1-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n1-sleep-diary",form_module:"local-sleep-s-n1-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n1-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n1-sleep-diary"},
        "local-sleep-s-n2-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n2-sleep-diary",form_module:"local-sleep-s-n2-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n2-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n2-sleep-diary"},
        "local-sleep-s-n3-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n3-sleep-diary",form_module:"local-sleep-s-n3-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n3-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n3-sleep-diary"},
        "local-sleep-s-n4-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n4-sleep-diary",form_module:"local-sleep-s-n4-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n4-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n4-sleep-diary"},
        "local-sleep-s-n5-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n5-sleep-diary",form_module:"local-sleep-s-n5-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n5-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n5-sleep-diary"},
        "local-sleep-s-n6-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n6-sleep-diary",form_module:"local-sleep-s-n6-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n6-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n6-sleep-diary"},
        "local-sleep-s-n7-sleep-diary-data":		                {url:" $H/m/library/ksd-data.html",Table:"local-sleep-s-n7-sleep-diary",form_module:"local-sleep-s-n7-sleep-diary-form",task_name:"Screening - Sleep Diary"},
        "local-sleep-s-n7-sleep-diary-form":		                {url:" $H/m/library/ksd-form.html",Table:"local-sleep-s-n7-sleep-diary"},
        "local-sleep-s-psg-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-s-psg-upload",form_module:"local-sleep-s-psg-upload-form",task_name:"Screening - PSG Diagnostic Report upload"},
        "local-sleep-s-psg-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-s-psg-upload"},
        "local-sleep-s-source-doc-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-s-source-doc",form_module:"local-sleep-s-source-doc-form",task_name:"Screening - Source Docs upload"},
        "local-sleep-s-source-doc-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-s-source-doc"},

        "local-sleep-b-d1-weight-bp-pm-data":		                {url:" $H/m/library/weight-bp-pm-data.html",Table:"local-sleep-b-d1-weight-bp-pm",form_module:"local-sleep-b-d1-weight-bp-pm-form",task_name:"Baseline Day 1 - Weight - Blood Pressure PM "},
        "local-sleep-b-d1-weight-bp-pm-form":		                {url:" $H/m/library/weight-bp-pm-form.html",Table:"local-sleep-b-d1-weight-bp-pm"},
        "local-sleep-b-ethnicity-data":		                        {url:" $H/m/library/ethnicity-data.html",Table:"local-sleep-b-ethnicity",form_module:"local-sleep-b-ethnicity-form",task_name:"Baseline Day 1 - Ethnicity"},
        "local-sleep-b-ethnicity-form":		                {url:" $H/m/library/ethnicity-form.html",Table:"local-sleep-b-ethnicity",task_name:"Ethnicity"},
        "local-sleep-b-lifestyle-data":		                        {url:" $H/m/library/lifestyle-data.html",Table:"local-sleep-b-lifestyle",form_module:"local-sleep-b-lifestyle-form",task_name:"Baseline Day 1 - Lifestyle"},
        "local-sleep-b-lifestyle-form":		                {url:" $H/m/library/lifestyle-form.html",Table:"local-sleep-b-lifestyle",task_name:"Lifestyle"},
        "local-sleep-b-education-data":		                        {url:" $H/m/library/education-data.html",Table:"local-sleep-b-education",form_module:"local-sleep-b-education-form",task_name:"Baseline Day 1 - Education"},
        "local-sleep-b-education-form":		                {url:" $H/m/library/education-form.html",Table:"local-sleep-b-education",task_name:"Education"},
        "local-sleep-b-d1-ess-data":		                {url:" $H/m/library/ess-data.html",Table:"local-sleep-b-d1-ess",form_module:"local-sleep-b-d1-ess-form",task_name:"Baseline Day 1 - ESS"},
        "local-sleep-b-d1-ess-form":		                {url:" $H/m/library/ess-form.html",Table:"local-sleep-b-d1-ess",task_name:"ESS"},
        "local-sleep-b-d1-dass-data":		                {url:" $H/m/library/dass-data.html",Table:"local-sleep-b-d1-dass",form_module:"local-sleep-b-d1-dass-form",task_name:"Baseline Day 1 - DASS"},
        "local-sleep-b-d1-dass-form":		                {url:" $H/m/library/dass-form.html",Table:"local-sleep-b-d1-dass",task_name:"DASS"},
        "local-sleep-b-d1-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-d1-cpap-upload",form_module:"local-sleep-b-d1-cpap-upload-form",task_name:"Baseline Day 1 - CPAP upload"},
        "local-sleep-b-d1-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-d1-cpap-upload"},
        "local-sleep-b-d1-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-b-d1-cpap",form_module:"local-sleep-b-d1-cpap-form",task_name:"Baseline Day 1 - CPAP"},
        "local-sleep-b-d1-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-b-d1-cpap"},

        "local-sleep-b-d2-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-b-d2-bp-am-pm",form_module:"local-sleep-b-d2-bp-am-pm-form",task_name:"Baseline Day 2 - Blood Pressure AM and PM "},
        "local-sleep-b-d2-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-b-d2-bp-am-pm"},
        "local-sleep-b-d2-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-d2-cpap-upload",form_module:"local-sleep-b-d2-cpap-upload-form",task_name:"Baseline Day 2 - CPAP upload"},
        "local-sleep-b-d2-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-d2-cpap-upload"},
        "local-sleep-b-d2-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-b-d2-cpap",form_module:"local-sleep-b-d2-cpap-form",task_name:"Baseline Day 2 - CPAP"},
        "local-sleep-b-d2-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-b-d2-cpap"},

        "local-sleep-b-d2-bla-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-bla-kss",form_module:"local-sleep-b-d2-bla-kss-form",task_name:"Baseline Day 2 BL1 - KSS Before PVT"},
        "local-sleep-b-d2-bla-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-bl-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d2-bl-pvt",form_module:"local-sleep-b-d2-bl-pvt-form",task_name:"Baseline Day 2 BL1 - PVT"},
        "local-sleep-b-d2-bl-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d2-bl-pvt",task_name:"Baseline Day 2 BL1 - PVT"},
        "local-sleep-b-d2-blb-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-blb-kss",form_module:"local-sleep-b-d2-blb-kss-form",task_name:"Baseline Day 2 BL1- KSS After PVT"},
        "local-sleep-b-d2-blb-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t1a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t1a-kss",form_module:"local-sleep-b-d2-t1a-kss-form",task_name:"Baseline Day 2 TB1 - KSS Before PVT"},
        "local-sleep-b-d2-t1a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t1-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d2-t1-pvt",form_module:"local-sleep-b-d2-t1-pvt-form",task_name:"Baseline Day 2 TB1 - PVT"},
        "local-sleep-b-d2-t1-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d2-t1-pvt"},
        "local-sleep-b-d2-t1b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t1b-kss",form_module:"local-sleep-b-d2-t1b-kss-form",task_name:"Baseline Day 2 TB1 - KSS After PVT"},
        "local-sleep-b-d2-t1b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t2a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t2a-kss",form_module:"local-sleep-b-d2-t2a-kss-form",task_name:"Baseline Day 2 TB2 - KSS Before PVT"},
        "local-sleep-b-d2-t2a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t2-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d2-t2-pvt",form_module:"local-sleep-b-d2-t2-pvt-form",task_name:"Baseline Day 2 TB2 - PVT"},
        "local-sleep-b-d2-t2-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d2-t2-pvt"},
        "local-sleep-b-d2-t2b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t2b-kss",form_module:"local-sleep-b-d2-t2b-kss-form",task_name:"Baseline Day 2 TB2 - KSS After PVT"},
        "local-sleep-b-d2-t2b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t3a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t3a-kss",form_module:"local-sleep-b-d2-t3a-kss-form",task_name:"Baseline Day 2 TB3 - KSS Before PVT"},
        "local-sleep-b-d2-t3a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t3-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d2-t3-pvt",form_module:"local-sleep-b-d2-t3-pvt-form",task_name:"Baseline Day 2 TB3 - PVT"},
        "local-sleep-b-d2-t3-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d2-t3-pvt"},
        "local-sleep-b-d2-t3b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t3b-kss",form_module:"local-sleep-b-d2-t3b-kss-form",task_name:"Baseline Day 2 TB3 - KSS After PVT"},
        "local-sleep-b-d2-t3b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t4a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t4a-kss",form_module:"local-sleep-b-d2-t4a-kss-form",task_name:"Baseline Day 2 TB4 - KSS Before PVT"},
        "local-sleep-b-d2-t4a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t4-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d2-t4-pvt",form_module:"local-sleep-b-d2-t4-pvt-form",task_name:"Baseline Day 2 TB4 - PVT"},
        "local-sleep-b-d2-t4-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d2-t4-pvt"},
        "local-sleep-b-d2-t4b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d2-t4b-kss",form_module:"local-sleep-b-d2-t4b-kss-form",task_name:"Baseline Day 2 TB4 - KSS After PVT"},
        "local-sleep-b-d2-t4b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d2-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d3-t5a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d3-t5a-kss",form_module:"local-sleep-b-d3-t5a-kss-form",task_name:"Baseline Day 3 TB5 - KSS Before PVT"},
        "local-sleep-b-d3-t5a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d3-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d3-t5-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-b-d3-t5-pvt",form_module:"local-sleep-b-d3-t5-pvt-form",task_name:"Baseline Day 3 TB5 - PVT"},
        "local-sleep-b-d3-t5-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-b-d3-t5-pvt"},
        "local-sleep-b-d3-t5b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-b-d3-t5b-kss",form_module:"local-sleep-b-d3-t5b-kss-form",task_name:"Baseline Day 3 TB5 - KSS After PVT"},
        "local-sleep-b-d3-t5b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-b-d3-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d3-bp-am-data":		                {url:" $H/m/library/bp-am-data.html",Table:"local-sleep-b-d3-bp-am",form_module:"local-sleep-b-d3-bp-am-form",task_name:"Baseline Day 3 - Blood Pressure AM"},
        "local-sleep-b-d3-bp-am-form":		                {url:" $H/m/library/bp-am-form.html",Table:"local-sleep-b-d3-bp-am"},

        "local-sleep-b-g1-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-b-g1-psg300",form_module:"local-sleep-b-g1-psg300-form",task_name:"Baseline General Night 1- Grael Research PSG Report"},
        "local-sleep-b-g1-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-b-g1-psg300",task_name:"Baseline General Night 1 - Grael Research PSG Report"},
        "local-sleep-b-g2-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-b-g2-psg300",form_module:"local-sleep-b-g2-psg300-form",task_name:"Baseline General Night 2- Grael Research PSG Report"},
        "local-sleep-b-g2-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-b-g2-psg300",task_name:"Baseline General Night 2 - Grael Research PSG Report"},
        "local-sleep-b-g1-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g1-psgedf",form_module:"local-sleep-b-g1-psgedf-form",task_name:"Baseline General Night 1- PSG EDF"},
        "local-sleep-b-g1-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g1-psgedf"},
        "local-sleep-b-g2-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g2-psgedf",form_module:"local-sleep-b-g2-psgedf-form",task_name:"Baseline General Night 2- PSG EDF"},
        "local-sleep-b-g2-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g2-psgedf"},
        "local-sleep-b-g1-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g1-sleep-scoring",form_module:"local-sleep-b-g1-sleep-scoring-form",task_name:"Baseline General Night 1- Sleep Scoring"},
        "local-sleep-b-g1-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g1-sleep-scoring"},
        "local-sleep-b-g2-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g2-sleep-scoring",form_module:"local-sleep-b-g2-sleep-scoring-form",task_name:"Baseline General Night 2- Sleep Scoring"},
        "local-sleep-b-g2-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g2-sleep-scoring"},
        "local-sleep-b-g-source-doc-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g-source-doc",form_module:"local-sleep-b-g-source-doc-form",task_name:"Baseline General - Source Documents"},
        "local-sleep-b-g-source-doc-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g-source-doc"},
        "local-sleep-b-g-sleep-diary-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g-sleep-diary",form_module:"local-sleep-b-g-sleep-diary-form",task_name:"Baseline General - Sleep Diary"},
        "local-sleep-b-g-sleep-diary-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g-sleep-diary"},
        "local-sleep-b-g-finapres-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g-finapres",form_module:"local-sleep-b-g-finapres-form",task_name:"Baseline General - Finapres"},
        "local-sleep-b-g-finapres-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g-finapres"},
        "local-sleep-b-g-geoscan-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-b-g-geoscan",form_module:"local-sleep-b-g-geoscan-form",task_name:"Baseline General - Geoscan"},
        "local-sleep-b-g-geoscan-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-b-g-geoscan"},

        "local-sleep-t1-d1-weight-bp-pm-data":		                {url:" $H/m/library/weight-bp-pm-data.html",Table:"local-sleep-t1-d1-weight-bp-pm",form_module:"local-sleep-t1-d1-weight-bp-pm-form",task_name:"Treatment 1 Day 1 - Weight - Blood Pressure PM "},
        "local-sleep-t1-d1-weight-bp-pm-form":		                {url:" $H/m/library/weight-bp-pm-form.html",Table:"local-sleep-t1-d1-weight-bp-pm"},
        "local-sleep-t1-d1-ess-data":		                {url:" $H/m/library/ess-data.html",Table:"local-sleep-t1-d1-ess",form_module:"local-sleep-t1-d1-ess-form",task_name:"Treatment 1 Day 1 - ESS"},
        "local-sleep-t1-d1-ess-form":		                {url:" $H/m/library/ess-form.html",Table:"local-sleep-t1-d1-ess",task_name:"ESS"},
        "local-sleep-t1-d1-dass-data":		                {url:" $H/m/library/dass-data.html",Table:"local-sleep-t1-d1-dass",form_module:"local-sleep-t1-d1-dass-form",task_name:"Treatment 1 Day 1 - DASS"},
        "local-sleep-t1-d1-dass-form":		                {url:" $H/m/library/dass-form.html",Table:"local-sleep-t1-d1-dass",task_name:"DASS"},
        "local-sleep-t1-d1-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-d1-cpap-upload",form_module:"local-sleep-t1-d1-cpap-upload-form",task_name:"Treatment 1 Day 1 - CPAP upload"},
        "local-sleep-t1-d1-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-d1-cpap-upload"},
        "local-sleep-t1-d1-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t1-d1-cpap",form_module:"local-sleep-t1-d1-cpap-form",task_name:"Treatment 1 Day 1 - CPAP"},
        "local-sleep-t1-d1-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t1-d1-cpap"},

        "local-sleep-t1-d2-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t1-d2-bp-am-pm",form_module:"local-sleep-t1-d2-bp-am-pm-form",task_name:"Treatment 1 Day 2 - Blood Pressure AM and PM "},
        "local-sleep-t1-d2-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t1-d2-bp-am-pm"},
        "local-sleep-t1-d2-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-d2-cpap-upload",form_module:"local-sleep-t1-d2-cpap-upload-form",task_name:"Treatment 1 Day 2 - CPAP upload"},
        "local-sleep-t1-d2-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-d2-cpap-upload"},
        "local-sleep-t1-d2-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t1-d2-cpap",form_module:"local-sleep-t1-d2-cpap-form",task_name:"Treatment 1 Day 2 - CPAP"},
        "local-sleep-t1-d2-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t1-d2-cpap"},

        "local-sleep-t1-d3-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t1-d3-bp-am-pm",form_module:"local-sleep-t1-d3-bp-am-pm-form",task_name:"Treatment 1 Day 3 - Blood Pressure AM and PM "},
        "local-sleep-t1-d3-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t1-d3-bp-am-pm"},
        "local-sleep-t1-d3-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-d3-cpap-upload",form_module:"local-sleep-t1-d3-cpap-upload-form",task_name:"Treatment 1 Day 3 - CPAP upload"},
        "local-sleep-t1-d3-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-d3-cpap-upload"},
        "local-sleep-t1-d3-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t1-d3-cpap",form_module:"local-sleep-t1-d3-cpap-form",task_name:"Treatment 1 Day 3 - CPAP"},
        "local-sleep-t1-d3-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t1-d3-cpap"},

        "local-sleep-t1-d4-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t1-d4-bp-am-pm",form_module:"local-sleep-t1-d4-bp-am-pm-form",task_name:"Treatment 1 Day 2 - Blood Pressure AM and PM "},
        "local-sleep-t1-d4-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t1-d4-bp-am-pm"},
        "local-sleep-t1-d4-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-d4-cpap-upload",form_module:"local-sleep-t1-d4-cpap-upload-form",task_name:"Treatment 1 Day 2 - CPAP upload"},
        "local-sleep-t1-d4-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-d4-cpap-upload"},
        "local-sleep-t1-d4-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t1-d4-cpap",form_module:"local-sleep-t1-d4-cpap-form",task_name:"Treatment 1 Day 2 - CPAP"},
        "local-sleep-t1-d4-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t1-d4-cpap"},

        "local-sleep-t1-d4-bla-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-bla-kss",form_module:"local-sleep-t1-d4-bla-kss-form",task_name:"Treatment 1 Day 2 BL - KSS Before PVT"},
        "local-sleep-t1-d4-bla-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-bl-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d4-bl-pvt",form_module:"local-sleep-t1-d4-bl-pvt-form",task_name:"Treatment 1 Day 2 BL - PVT"},
        "local-sleep-t1-d4-bl-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d4-bl-pvt",task_name:"Treatment 1 Day 2 BL - KSS Before PVT"},
        "local-sleep-t1-d4-blb-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-blb-kss",form_module:"local-sleep-t1-d4-blb-kss-form",task_name:"Treatment 1 Day 2 BL - KSS After PVT"},
        "local-sleep-t1-d4-blb-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t1a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t1a-kss",form_module:"local-sleep-t1-d4-t1a-kss-form",task_name:"Treatment 1 Day 2 TB1 - KSS Before PVT"},
        "local-sleep-t1-d4-t1a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t1-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d4-t1-pvt",form_module:"local-sleep-t1-d4-t1-pvt-form",task_name:"Treatment 1 Day 2 TB1 - PVT"},
        "local-sleep-t1-d4-t1-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d4-t1-pvt",task_name:"Treatment 1 Day 2 TB1 - PVT"},
        "local-sleep-t1-d4-t1b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t1b-kss",form_module:"local-sleep-t1-d4-t1b-kss-form",task_name:"Treatment 1 Day 2 TB1 - KSS After PVT"},
        "local-sleep-t1-d4-t1b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t2a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t2a-kss",form_module:"local-sleep-t1-d4-t2a-kss-form",task_name:"Treatment 1 Day 2 TB2 - KSS Before PVT"},
        "local-sleep-t1-d4-t2a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t2-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d4-t2-pvt",form_module:"local-sleep-t1-d4-t2-pvt-form",task_name:"Treatment 1 Day 2 TB2 - PVT"},
        "local-sleep-t1-d4-t2-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d4-t2-pvt",task_name:"Treatment 1 Day 2 TB2 - PVT"},
        "local-sleep-t1-d4-t2b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t2b-kss",form_module:"local-sleep-t1-d4-t2b-kss-form",task_name:"Treatment 1 Day 2 TB2 - KSS After PVT"},
        "local-sleep-t1-d4-t2b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t3a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t3a-kss",form_module:"local-sleep-t1-d4-t3a-kss-form",task_name:"Treatment 1 Day 2 TB3 - KSS Before PVT"},
        "local-sleep-t1-d4-t3a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t3-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d4-t3-pvt",form_module:"local-sleep-t1-d4-t3-pvt-form",task_name:"Treatment 1 Day 2 TB3 - PVT"},
        "local-sleep-t1-d4-t3-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d4-t3-pvt",task_name:"Treatment 1 Day 2 TB3 - PVT"},
        "local-sleep-t1-d4-t3b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t3b-kss",form_module:"local-sleep-t1-d4-t3b-kss-form",task_name:"Treatment 1 Day 2 TB3 - KSS After PVT"},
        "local-sleep-t1-d4-t3b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t4a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t4a-kss",form_module:"local-sleep-t1-d4-t4a-kss-form",task_name:"Treatment 1 Day 2 TB4 - KSS Before PVT"},
        "local-sleep-t1-d4-t4a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t4-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d4-t4-pvt",form_module:"local-sleep-t1-d4-t4-pvt-form",task_name:"Treatment 1 Day 2 TB4 - PVT"},
        "local-sleep-t1-d4-t4-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d4-t4-pvt",task_name:"Treatment 1 Day 2 TB4 - PVT"},
        "local-sleep-t1-d4-t4b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d4-t4b-kss",form_module:"local-sleep-t1-d4-t4b-kss-form",task_name:"Treatment 1 Day 2 TB4 - KSS After PVT"},
        "local-sleep-t1-d4-t4b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d4-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d5-t5a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d5-t5a-kss",form_module:"local-sleep-t1-d5-t5a-kss-form",task_name:"Treatment 1 Day 3 TB5 - KSS Before PVT"},
        "local-sleep-t1-d5-t5a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d5-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d5-t5-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t1-d5-t5-pvt",form_module:"local-sleep-t1-d5-t5-pvt-form",task_name:"Treatment 1 Day 3 TB5 - PVT"},
        "local-sleep-t1-d5-t5-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t1-d5-t5-pvt",task_name:"Treatment 1 Day 3 TB5 - PVT"},
        "local-sleep-t1-d5-t5b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t1-d5-t5b-kss",form_module:"local-sleep-t1-d5-t5b-kss-form",task_name:"Treatment 1 Day 3 TB5 - KSS After PVT"},
        "local-sleep-t1-d5-t5b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t1-d5-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d5-bp-am-data":		    {url:" $H/m/library/bp-am-data.html",Table:"local-sleep-t1-d5-bp-am",form_module:"local-sleep-t1-d5-bp-am-form",task_name:"Treatment 1 Day 3 - Blood Pressure AM"},
        "local-sleep-t1-d5-bp-am-form":		    {url:" $H/m/library/bp-am-form.html",Table:"local-sleep-t1-d5-bp-am"},
 
        "local-sleep-t1-g1-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-t1-g1-psg300",form_module:"local-sleep-t1-g1-psg300-form",task_name:"Treatment 1 General Night 1 - Grael Research PSG Report"},
        "local-sleep-t1-g1-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-t1-g1-psg300",task_name:"Treatment 1 General Night 1 - Grael Research PSG Report"},
        "local-sleep-t1-g2-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-t1-g2-psg300",form_module:"local-sleep-t1-g2-psg300-form",task_name:"Treatment 1 General Night 2 - Grael Research PSG Report"},
        "local-sleep-t1-g2-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-t1-g2-psg300",task_name:"Treatment 1 General Night 2 - Grael Research PSG Report"},
        "local-sleep-t1-g1-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g1-psgedf",form_module:"local-sleep-t1-g1-psgedf-form",task_name:"Treatment 1 General Night 1 - PSG EDF"},
        "local-sleep-t1-g1-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g1-psgedf"},
        "local-sleep-t1-g2-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g2-psgedf",form_module:"local-sleep-t1-g2-psgedf-form",task_name:"Treatment 1 General Night 2 - PSG EDF"},
        "local-sleep-t1-g2-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g2-psgedf"},
        "local-sleep-t1-g1-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g1-sleep-scoring",form_module:"local-sleep-t1-g1-sleep-scoring-form",task_name:"Treatment 1 General Night 1 - Sleep Scoring"},
        "local-sleep-t1-g1-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g1-sleep-scoring"},
        "local-sleep-t1-g2-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g2-sleep-scoring",form_module:"local-sleep-t1-g2-sleep-scoring-form",task_name:"Treatment 1 General Night 2 - Sleep Scoring"},
        "local-sleep-t1-g2-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g2-sleep-scoring"},
        "local-sleep-t1-g-source-doc-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g-source-doc",form_module:"local-sleep-t1-g-source-doc-form",task_name:"Treatment 1 General - Source Document"},
        "local-sleep-t1-g-source-doc-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g-source-doc"},
        "local-sleep-t1-g-sleep-diary-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g-sleep-diary",form_module:"local-sleep-t1-g-sleep-diary-form",task_name:"Treatment 1 General - Sleep Diary"},
        "local-sleep-t1-g-sleep-diary-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g-sleep-diary"},
        "local-sleep-t1-g-finapres-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g-finapres",form_module:"local-sleep-t1-g-finapres-form",task_name:"Treatment 1 General - Finapres"},
        "local-sleep-t1-g-finapres-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g-finapres"},
        "local-sleep-t1-g-geoscan-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t1-g-geoscan",form_module:"local-sleep-t1-g-geoscan-form",task_name:"Treatment 1 General - Geoscan"},
        "local-sleep-t1-g-geoscan-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t1-g-geoscan"},

        "local-sleep-t2-d1-weight-bp-pm-data":		                {url:" $H/m/library/weight-bp-pm-data.html",Table:"local-sleep-t2-d1-weight-bp-pm",form_module:"local-sleep-t2-d1-weight-bp-pm-form",task_name:"Treatment 2 Day 1 - Weight - Blood Pressure PM "},
        "local-sleep-t2-d1-weight-bp-pm-form":		                {url:" $H/m/library/weight-bp-pm-form.html",Table:"local-sleep-t2-d1-weight-bp-pm"},
        "local-sleep-t2-d1-ess-data":		                {url:" $H/m/library/ess-data.html",Table:"local-sleep-t2-d1-ess",form_module:"local-sleep-t2-d1-ess-form",task_name:"Treatment 2 Day 1 - ESS"},
        "local-sleep-t2-d1-ess-form":		                {url:" $H/m/library/ess-form.html",Table:"local-sleep-t2-d1-ess",task_name:"ESS"},
        "local-sleep-t2-d1-dass-data":		                {url:" $H/m/library/dass-data.html",Table:"local-sleep-t2-d1-dass",form_module:"local-sleep-t2-d1-dass-form",task_name:"Treatment 2 Day 1 - DASS"},
        "local-sleep-t2-d1-dass-form":		                {url:" $H/m/library/dass-form.html",Table:"local-sleep-t2-d1-dass",task_name:"DASS"},
        "local-sleep-t2-d1-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-d1-cpap-upload",form_module:"local-sleep-t2-d1-cpap-upload-form",task_name:"Treatment 2 Day 1 - CPAP upload"},
        "local-sleep-t2-d1-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-d1-cpap-upload"},
        "local-sleep-t2-d1-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t2-d1-cpap",form_module:"local-sleep-t2-d1-cpap-form",task_name:"Treatment 2 Day 1 - CPAP"},
        "local-sleep-t2-d1-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t2-d1-cpap"},

        "local-sleep-t2-d2-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t2-d2-bp-am-pm",form_module:"local-sleep-t2-d2-bp-am-pm-form",task_name:"Treatment 2 Day 2 - Blood Pressure AM and PM "},
        "local-sleep-t2-d2-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t2-d2-bp-am-pm"},
        "local-sleep-t2-d2-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-d2-cpap-upload",form_module:"local-sleep-t2-d2-cpap-upload-form",task_name:"Treatment 2 Day 2 - CPAP upload"},
        "local-sleep-t2-d2-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-d2-cpap-upload"},
        "local-sleep-t2-d2-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t2-d2-cpap",form_module:"local-sleep-t2-d2-cpap-form",task_name:"Treatment 2 Day 2 - CPAP"},
        "local-sleep-t2-d2-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t2-d2-cpap"},

        "local-sleep-t2-d3-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t2-d3-bp-am-pm",form_module:"local-sleep-t2-d3-bp-am-pm-form",task_name:"Treatment 2 Day 3 - Blood Pressure AM and PM "},
        "local-sleep-t2-d3-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t2-d3-bp-am-pm"},
        "local-sleep-t2-d3-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-d3-cpap-upload",form_module:"local-sleep-t2-d3-cpap-upload-form",task_name:"Treatment 2 Day 3 - CPAP upload"},
        "local-sleep-t2-d3-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-d3-cpap-upload"},
        "local-sleep-t2-d3-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t2-d3-cpap",form_module:"local-sleep-t2-d3-cpap-form",task_name:"Treatment 2 Day 3 - CPAP"},
        "local-sleep-t2-d3-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t2-d3-cpap"},

        "local-sleep-t2-d4-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-t2-d4-bp-am-pm",form_module:"local-sleep-t2-d4-bp-am-pm-form",task_name:"Treatment 2 Day 2 - Blood Pressure AM and PM "},
        "local-sleep-t2-d4-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-t2-d4-bp-am-pm"},
        "local-sleep-t2-d4-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-d4-cpap-upload",form_module:"local-sleep-t2-d4-cpap-upload-form",task_name:"Treatment 2 Day 2 - CPAP upload"},
        "local-sleep-t2-d4-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-d4-cpap-upload"},
        "local-sleep-t2-d4-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-t2-d4-cpap",form_module:"local-sleep-t2-d4-cpap-form",task_name:"Treatment 2 Day 2 - CPAP"},
        "local-sleep-t2-d4-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-t2-d4-cpap"},

        "local-sleep-t2-d4-bla-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-bla-kss",form_module:"local-sleep-t2-d4-bla-kss-form",task_name:"Treatment 2 Day 2 BL - KSS Before PVT"},
        "local-sleep-t2-d4-bla-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-bl-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d4-bl-pvt",form_module:"local-sleep-t2-d4-bl-pvt-form",task_name:"Treatment 2 Day 2 BL - PVT"},
        "local-sleep-t2-d4-bl-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d4-bl-pvt",task_name:"Treatment 2 Day 2 BL - PVT"},
        "local-sleep-t2-d4-blb-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-blb-kss",form_module:"local-sleep-t2-d4-blb-kss-form",task_name:"Treatment 2 Day 2 BL - KSS After PVT"},
        "local-sleep-t2-d4-blb-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t1a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t1a-kss",form_module:"local-sleep-t2-d4-t1a-kss-form",task_name:"Treatment 2 Day 2 TB1 - KSS Before PVT"},
        "local-sleep-t2-d4-t1a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t1-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d4-t1-pvt",form_module:"local-sleep-t2-d4-t1-pvt-form",task_name:"Treatment 2 Day 2 TB1 - PVT"},
        "local-sleep-t2-d4-t1-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d4-t1-pvt",task_name:"Treatment 2 Day 2 TB1 - PVT"},
        "local-sleep-t2-d4-t1b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t1b-kss",form_module:"local-sleep-t2-d4-t1b-kss-form",task_name:"Treatment 2 Day 2 TB1 - KSS After PVT"},
        "local-sleep-t2-d4-t1b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t2a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t2a-kss",form_module:"local-sleep-t2-d4-t2a-kss-form",task_name:"Treatment 2 Day 2 TB2 - KSS Before PVT"},
        "local-sleep-t2-d4-t2a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t2-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d4-t2-pvt",form_module:"local-sleep-t2-d4-t2-pvt-form",task_name:"Treatment 2 Day 2 TB2 - PVT"},
        "local-sleep-t2-d4-t2-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d4-t2-pvt",task_name:"Treatment 2 Day 2 TB2 - PVT"},
        "local-sleep-t2-d4-t2b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t2b-kss",form_module:"local-sleep-t2-d4-t2b-kss-form",task_name:"Treatment 2 Day 2 TB2 - KSS After PVT"},
        "local-sleep-t2-d4-t2b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t3a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t3a-kss",form_module:"local-sleep-t2-d4-t3a-kss-form",task_name:"Treatment 2 Day 2 TB3 - KSS Before PVT"},
        "local-sleep-t2-d4-t3a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t3-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d4-t3-pvt",form_module:"local-sleep-t2-d4-t3-pvt-form",task_name:"Treatment 2 Day 2 TB3 - PVT"},
        "local-sleep-t2-d4-t3-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d4-t3-pvt",task_name:"Treatment 2 Day 2 TB3 - PVT"},
        "local-sleep-t2-d4-t3b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t3b-kss",form_module:"local-sleep-t2-d4-t3b-kss-form",task_name:"Treatment 2 Day 2 TB3 - KSS After PVT"},
        "local-sleep-t2-d4-t3b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t4a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t4a-kss",form_module:"local-sleep-t2-d4-t4a-kss-form",task_name:"Treatment 2 Day 2 TB4 - KSS Before PVT"},
        "local-sleep-t2-d4-t4a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t4-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d4-t4-pvt",form_module:"local-sleep-t2-d4-t4-pvt-form",task_name:"Treatment 2 Day 2 TB4 - PVT"},
        "local-sleep-t2-d4-t4-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d4-t4-pvt",task_name:"Treatment 2 Day 2 TB4 - PVT"},
        "local-sleep-t2-d4-t4b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d4-t4b-kss",form_module:"local-sleep-t2-d4-t4b-kss-form",task_name:"Treatment 2 Day 2 TB4 - KSS After PVT"},
        "local-sleep-t2-d4-t4b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d4-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d5-t5a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d5-t5a-kss",form_module:"local-sleep-t2-d5-t5a-kss-form",task_name:"Treatment 2 Day 3 TB5 - KSS Before PVT"},
        "local-sleep-t2-d5-t5a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d5-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d5-t5-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-t2-d5-t5-pvt",form_module:"local-sleep-t2-d5-t5-pvt-form",task_name:"Treatment 2 Day 3 TB5 - PVT"},
        "local-sleep-t2-d5-t5-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-t2-d5-t5-pvt",task_name:"Treatment 2 Day 3 TB5 - PVT"},
        "local-sleep-t2-d5-t5b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-t2-d5-t5b-kss",form_module:"local-sleep-t2-d5-t5b-kss-form",task_name:"Treatment 2 Day 3 TB5 - KSS After PVT"},
        "local-sleep-t2-d5-t5b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-t2-d5-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d5-bp-am-data":		                {url:" $H/m/library/bp-am-data.html",Table:"local-sleep-t2-d5-bp-am",form_module:"local-sleep-t2-d5-bp-am-form",task_name:"Treatment 2 Day 3 - Blood Pressure AM"},
        "local-sleep-t2-d5-bp-am-form":		                {url:" $H/m/library/bp-am-form.html",Table:"local-sleep-t2-d5-bp-am"},

        "local-sleep-t2-g1-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-t2-g1-psg300",form_module:"local-sleep-t2-g1-psg300-form",task_name:"Treatment 2 General Night 1 - Grael Research PSG Report"},
        "local-sleep-t2-g1-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-t2-g1-psg300",task_name:"Treatment 2 General Night 1 - Grael Research PSG Report"},
        "local-sleep-t2-g2-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-t2-g2-psg300",form_module:"local-sleep-t2-g2-psg300-form",task_name:"Treatment 2 General Night 2 - Grael Research PSG Report"},
        "local-sleep-t2-g2-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-t2-g2-psg300",task_name:"Treatment 2 General Night 2 - Grael Research PSG Report"},
        "local-sleep-t2-g1-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g1-psgedf",form_module:"local-sleep-t2-g1-psgedf-form",task_name:"Treatment 2 General Night 1 - PSG EDF"},
        "local-sleep-t2-g1-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g1-psgedf"},
        "local-sleep-t2-g2-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g2-psgedf",form_module:"local-sleep-t2-g2-psgedf-form",task_name:"Treatment 2 General Night 2 - PSG EDF"},
        "local-sleep-t2-g2-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g2-psgedf"},
        "local-sleep-t2-g1-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g1-sleep-scoring",form_module:"local-sleep-t2-g1-sleep-scoring-form",task_name:"Treatment 2 General Night 1 - Sleep Scoring"},
        "local-sleep-t2-g1-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g1-sleep-scoring"},
        "local-sleep-t2-g2-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g2-sleep-scoring",form_module:"local-sleep-t2-g2-sleep-scoring-form",task_name:"Treatment 2 General Night 2 - Sleep Scoring"},
        "local-sleep-t2-g2-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g2-sleep-scoring"},
        "local-sleep-t2-g-source-doc-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g-source-doc",form_module:"local-sleep-t2-g-source-doc-form",task_name:"Treatment 2 General - Source Document"},
        "local-sleep-t2-g-source-doc-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g-source-doc"},
        "local-sleep-t2-g-sleep-diary-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g-sleep-diary",form_module:"local-sleep-t2-g-sleep-diary-form",task_name:"Treatment 2 General - Sleep Diary"},
        "local-sleep-t2-g-sleep-diary-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g-sleep-diary"},
        "local-sleep-t2-g-finapres-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g-finapres",form_module:"local-sleep-t2-g-finapres-form",task_name:"Treatment 2 General - Finapres"},
        "local-sleep-t2-g-finapres-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g-finapres"},
        "local-sleep-t2-g-geoscan-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-t2-g-geoscan",form_module:"local-sleep-t2-g-geoscan-form",task_name:"Treatment 2 General - Geoscan"},
        "local-sleep-t2-g-geoscan-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-t2-g-geoscan"},

        "local-sleep-fu-d1-weight-bp-pm-data":		                {url:" $H/m/library/weight-bp-pm-data.html",Table:"local-sleep-fu-d1-weight-bp-pm",form_module:"local-sleep-fu-d1-weight-bp-pm-form",task_name:"Follow up Day 1 - Weight - Blood Pressure PM "},
        "local-sleep-fu-d1-weight-bp-pm-form":		                {url:" $H/m/library/weight-bp-pm-form.html",Table:"local-sleep-fu-d1-weight-bp-pm"},
        "local-sleep-fu-d1-ess-data":		                {url:" $H/m/library/ess-data.html",Table:"local-sleep-fu-d1-ess",form_module:"local-sleep-fu-d1-ess-form",task_name:"Follow up Day 1 - ESS"},
        "local-sleep-fu-d1-ess-form":		                {url:" $H/m/library/ess-form.html",Table:"local-sleep-fu-d1-ess",task_name:"ESS"},
        "local-sleep-fu-d1-dass-data":		                {url:" $H/m/library/dass-data.html",Table:"local-sleep-fu-d1-dass",form_module:"local-sleep-fu-d1-dass-form",task_name:"Follow up Day 1 - DASS"},
        "local-sleep-fu-d1-dass-form":		                {url:" $H/m/library/dass-form.html",Table:"local-sleep-fu-d1-dass",task_name:"DASS"},
        "local-sleep-fu-d1-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-d1-cpap-upload",form_module:"local-sleep-fu-d1-cpap-upload-form",task_name:"Follow up Day 1 - CPAP upload"},
        "local-sleep-fu-d1-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-d1-cpap-upload"},
        "local-sleep-fu-d1-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-fu-d1-cpap",form_module:"local-sleep-fu-d1-cpap-form",task_name:"Follow up Day 1 - CPAP"},
        "local-sleep-fu-d1-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-fu-d1-cpap"},

        "local-sleep-fu-d2-bp-am-pm-data":		                {url:" $H/m/library/bp-am-pm-data.html",Table:"local-sleep-fu-d2-bp-am-pm",form_module:"local-sleep-fu-d2-bp-am-pm-form",task_name:"Follow up Day 2 - Blood Pressure AM and PM "},
        "local-sleep-fu-d2-bp-am-pm-form":		                {url:" $H/m/library/bp-am-pm-form.html",Table:"local-sleep-fu-d2-bp-am-pm"},
        "local-sleep-fu-d2-cpap-upload-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-d2-cpap-upload",form_module:"local-sleep-fu-d2-cpap-upload-form",task_name:"Follow up Day 2 - CPAP upload"},
        "local-sleep-fu-d2-cpap-upload-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-d2-cpap-upload"},
        "local-sleep-fu-d2-cpap-data":		                {url:" $H/m/library/cpap-data.html",Table:"local-sleep-fu-d2-cpap",form_module:"local-sleep-fu-d2-cpap-form",task_name:"Follow up Day 2 - CPAP"},
        "local-sleep-fu-d2-cpap-form":		                {url:" $H/m/library/cpap-form.html",Table:"local-sleep-fu-d2-cpap"},

        "local-sleep-fu-d2-bla-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-bla-kss",form_module:"local-sleep-fu-d2-bla-kss-form",task_name:"Follow up Day 2 BL - KSS Before PVT"},
        "local-sleep-fu-d2-bla-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-bl-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d2-bl-pvt",form_module:"local-sleep-fu-d2-bl-pvt-form",task_name:"Follow up Day 2 BL - PVT"},
        "local-sleep-fu-d2-bl-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d2-bl-pvt"},
        "local-sleep-fu-d2-blb-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-blb-kss",form_module:"local-sleep-fu-d2-blb-kss-form",task_name:"Follow up Day 2 BL - KSS After PVT"},
        "local-sleep-fu-d2-blb-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t1a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t1a-kss",form_module:"local-sleep-fu-d2-t1a-kss-form",task_name:"Follow up Day 2 TP1 - KSS Before PVT"},
        "local-sleep-fu-d2-t1a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t1-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d2-t1-pvt",form_module:"local-sleep-fu-d2-t1-pvt-form",task_name:"Follow up Day 2 TP1 - PVT"},
        "local-sleep-fu-d2-t1-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d2-t1-pvt"},
        "local-sleep-fu-d2-t1b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t1b-kss",form_module:"local-sleep-fu-d2-t1b-kss-form",task_name:"Follow up Day 2 TP1 - KSS After PVT"},
        "local-sleep-fu-d2-t1b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t2a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t2a-kss",form_module:"local-sleep-fu-d2-t2a-kss-form",task_name:"Follow up Day 2 TP2 - KSS Before PVT"},
        "local-sleep-fu-d2-t2a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t2-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d2-t2-pvt",form_module:"local-sleep-fu-d2-t2-pvt-form",task_name:"Follow up Day 2 TP2 - PVT"},
        "local-sleep-fu-d2-t2-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d2-t2-pvt"},
        "local-sleep-fu-d2-t2b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t2b-kss",form_module:"local-sleep-fu-d2-t2b-kss-form",task_name:"Follow up Day 2 TP2 - KSS After PVT"},
        "local-sleep-fu-d2-t2b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t3a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t3a-kss",form_module:"local-sleep-fu-d2-t3a-kss-form",task_name:"Follow up Day 2 TP3 - KSS Before PVT"},
        "local-sleep-fu-d2-t3a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t3-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d2-t3-pvt",form_module:"local-sleep-fu-d2-t3-pvt-form",task_name:"Follow up Day 2 TP3 - PVT"},
        "local-sleep-fu-d2-t3-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d2-t3-pvt"},
        "local-sleep-fu-d2-t3b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t3b-kss",form_module:"local-sleep-fu-d2-t3b-kss-form",task_name:"Follow up Day 2 TP3 - KSS After PVT"},
        "local-sleep-fu-d2-t3b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t4a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t4a-kss",form_module:"local-sleep-fu-d2-t4a-kss-form",task_name:"Follow up Day 2 TP4 - KSS Before PVT"},
        "local-sleep-fu-d2-t4a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t4-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d2-t4-pvt",form_module:"local-sleep-fu-d2-t4-pvt-form",task_name:"Follow up Day 2 TP4 - PVT"},
        "local-sleep-fu-d2-t4-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d2-t4-pvt"},
        "local-sleep-fu-d2-t4b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d2-t4b-kss",form_module:"local-sleep-fu-d2-t4b-kss-form",task_name:"Follow up Day 2 TP4 - KSS After PVT"},
        "local-sleep-fu-d2-t4b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d3-t5a-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d3-t5a-kss",form_module:"local-sleep-fu-d3-t5a-kss-form",task_name:"Follow up Day 3 TP5 - KSS Before PVT"},
        "local-sleep-fu-d3-t5a-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d3-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d3-t5-pvt-data":		                {url:" $H/m/library/pvt-pc-data.html",Table:"local-sleep-fu-d3-t5-pvt",form_module:"local-sleep-fu-d3-t5-pvt-form",task_name:"Follow up Day 3 TP5 - PVT"},
        "local-sleep-fu-d3-t5-pvt-form":		                {url:" $H/m/library/pvt-pc-form.html",Table:"local-sleep-fu-d3-t5-pvt"},
        "local-sleep-fu-d3-t5b-kss-data":		                {url:" $H/m/library/kss-data.html",Table:"local-sleep-fu-d3-t5b-kss",form_module:"local-sleep-fu-d3-t5b-kss-form",task_name:"Follow up Day 3 TP5 - KSS After PVT"},
        "local-sleep-fu-d3-t5b-kss-form":		                {url:" $H/m/library/kss-form.html",Table:"local-sleep-fu-d2-t45-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d3-bp-am-data":		                {url:" $H/m/library/bp-am-data.html",Table:"local-sleep-fu-d3-bp-am",form_module:"local-sleep-fu-d3-bp-am-form",task_name:"Follow up Day 3 - Blood Pressure AM"},
        "local-sleep-fu-d3-bp-am-form":		                {url:" $H/m/library/bp-am-form.html",Table:"local-sleep-fu-d3-bp-am"},
 
        "local-sleep-fu-g1-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-fu-g1-psg300",form_module:"local-sleep-fu-g1-psg300-form",task_name:"Follow up General Night 1 - Grael Research PSG Report"},
        "local-sleep-fu-g1-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-fu-g1-psg300",task_name:"Follow up General Night 1 - Grael Research PSG Report"},
        "local-sleep-fu-g2-psg300-data":		                {url:" $H/m/library/psg300-data.html",Table:"local-sleep-fu-g2-psg300",form_module:"local-sleep-fu-g2-psg300-form",task_name:"Follow up General Night 2 - Grael Research PSG Report"},
        "local-sleep-fu-g2-psg300-form":		                {url:" $H/m/library/psg300-form.html",Table:"local-sleep-fu-g2-psg300",task_name:"Follow up General Night 2 - Grael Research PSG Report"},
        "local-sleep-fu-g1-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g1-psgedf",form_module:"local-sleep-fu-g1-psgedf-form",task_name:"Follow up General Night 1 - PSG EDF"},
        "local-sleep-fu-g1-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g1-psgedf"},
        "local-sleep-fu-g2-psgedf-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g2-psgedf",form_module:"local-sleep-fu-g2-psgedf-form",task_name:"Follow up General Night 2 - PSG EDF"},
        "local-sleep-fu-g2-psgedf-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g2-psgedf"},
        "local-sleep-fu-g1-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g1-sleep-scoring",form_module:"local-sleep-fu-g1-sleep-scoring-form",task_name:"Follow up General Night 1 - Sleep Scoring"},
        "local-sleep-fu-g1-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g1-sleep-scoring"},
        "local-sleep-fu-g2-sleep-scoring-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g2-sleep-scoring",form_module:"local-sleep-fu-g2-sleep-scoring-form",task_name:"Follow up General Night 2 - Sleep Scoring"},
        "local-sleep-fu-g2-sleep-scoring-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g2-sleep-scoring"},
        "local-sleep-fu-g-source-doc-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g-source-doc",form_module:"local-sleep-fu-g-source-doc-form",task_name:"Follow up General - Source Document"},
        "local-sleep-fu-g-source-doc-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g-source-doc"},
        "local-sleep-fu-g-sleep-diary-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g-sleep-diary",form_module:"local-sleep-fu-g-sleep-diary-form",task_name:"Follow up General - Sleep Diary"},
        "local-sleep-fu-g-sleep-diary-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g-sleep-diary"},
        "local-sleep-fu-g-finapres-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g-finapres",form_module:"local-sleep-fu-g-finapres-form",task_name:"Follow up General - Finapres"},
        "local-sleep-fu-g-finapres-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g-finapres"},
        "local-sleep-fu-g-geoscan-data":		                {url:" $H/m/library/upload-file-data.html",Table:"local-sleep-fu-g-geoscan",form_module:"local-sleep-fu-g-geoscan-form",task_name:"Follow up General - Geoscan"},
        "local-sleep-fu-g-geoscan-form":		                {url:" $H/m/library/upload-file-form.html",Table:"local-sleep-fu-g-geoscan"},

        "local-sleep-b-d2-1-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-b-d2-1-aused-90",form_module:"local-sleep-b-d2-1-aused-90-form",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-b-d2-1-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-b-d2-1-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-b-d2-2-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-b-d2-2-aused-90",form_module:"local-sleep-b-d2-2-aused-90-form",task_name:"Baseline Day 2 Drv 2 - Aused"},
        "local-sleep-b-d2-2-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-b-d2-2-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-b-d2-3-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-b-d2-3-aused-90",form_module:"local-sleep-b-d2-3-aused-90-form",task_name:"Baseline Day 2 Drv 3 - Aused"},
        "local-sleep-b-d2-3-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-b-d2-3-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t1-d4-1-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t1-d4-1-aused-90",form_module:"local-sleep-t1-d4-1-aused-90-form",task_name:"Treatment 1 Day 2 Drv 1 - Aused"},
        "local-sleep-t1-d4-1-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t1-d4-1-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t1-d4-2-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t1-d4-2-aused-90",form_module:"local-sleep-t1-d4-2-aused-90-form",task_name:"Treatment 1 Day 2 Drv 2 - Aused"},
        "local-sleep-t1-d4-2-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t1-d4-2-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t1-d4-3-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t1-d4-3-aused-90",form_module:"local-sleep-t1-d4-3-aused-90-form",task_name:"Treatment 1 Day 2 Drv 3 - Aused"},
        "local-sleep-t1-d4-3-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t1-d4-3-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t2-d4-1-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t2-d4-1-aused-90",form_module:"local-sleep-t2-d4-1-aused-90-form",task_name:"Treatment 2 Day 2 Drv 1 - Aused"},
        "local-sleep-t2-d4-1-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t2-d4-1-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t2-d4-2-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t2-d4-2-aused-90",form_module:"local-sleep-t2-d4-2-aused-90-form",task_name:"Treatment 2 Day 2 Drv 2 - Aused"},
        "local-sleep-t2-d4-2-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t2-d4-2-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-t2-d4-3-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-t2-d4-3-aused-90",form_module:"local-sleep-t2-d4-3-aused-90-form",task_name:"Treatment 2 Day 2 Drv 3 - Aused"},
        "local-sleep-t2-d4-3-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-t2-d4-3-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-fu-d2-1-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-fu-d2-1-aused-90",form_module:"local-sleep-fu-d2-1-aused-90-form",task_name:"Follow up Day 2 Drv 1 - Aused"},
        "local-sleep-fu-d2-1-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-fu-d2-1-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-fu-d2-2-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-fu-d2-2-aused-90",form_module:"local-sleep-fu-d2-2-aused-90-form",task_name:"Follow up Day 2 Drv 2 - Aused"},
        "local-sleep-fu-d2-2-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-fu-d2-2-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},
        "local-sleep-fu-d2-3-aused-90-data":		                {url:" $H/m/library/aused90-data.html",Table:"local-sleep-fu-d2-3-aused-90",form_module:"local-sleep-fu-d2-3-aused-90-form",task_name:"Follow up Day 2 Drv 3 - Aused"},
        "local-sleep-fu-d2-3-aused-90-form":		                {url:" $H/m/library/aused90-form.html",Table:"local-sleep-fu-d2-3-aused-90",task_name:"Baseline Day 2 Drv 1 - Aused"},

    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.hosting_path=$vm.hosting_path.replace('online-questionnaire','')
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
    }

})();
