(function(){
    var modules={
        "panel-main-local-sleep":    			{url:"$A/components/panel/panel-main.html",router:1},
        "panel-child-local-sleep":    			{url:"$A/components/panel/panel-child.html"},
        
        "participant-data":   		{url:"$A/components/participant/participant-data.html",Table:"local-sleep-participant",form_module:"participant-form",router:1,
                                            child_panel:"panel-child-local-sleep",
                                            questionnaire_setup:"online-questionnaire-setup-local-sleep",
                                            online_questionnaire:"online-questionnaire-app-local-sleep",
                                            participant_id:{field1:"Subject_ID",field2:"Subject_Initials"}
                                        },
        "participant-form":   		{url:"$A/components/participant/participant-form.html",Table:"local-sleep-participant"},

        "online-questionnaire-setup-local-sleep": 	{url:"$A/modulesnline-questionnaire/components/modulesnline-questionnaire-setup.html",Table:"local-sleep-participant"},
        "online-questionnaire-app-local-sleep":    {url:"$A/modulesnline-questionnaire/index.html"},

        "notes":  		  	  			{url:"$A/modules/notes.html"},

        "local-sleep-randomisation-table-data":		    {url:"$A/modules/randomisation-table-data.html",Table:"local-sleep-randomisation-table",form_module:"local-sleep-randomisation-table-form"},
        "local-sleep-randomisation-table-form":		    {url:"$A/modules/randomisation-table-form.html",Table:"local-sleep-randomisation-table"},
        "local-sleep-concom-medication-data":            {url:"$A/modules/concom-medication-data.html",Table:"local-sleep-concom-medication",form_module:"local-sleep-concom-medication-form"},
        "local-sleep-concom-medication-form":            {url:"$A/modules/concom-medication-form.html",Table:"local-sleep-concom-medication"},
        "local-sleep-adverse-event-data":                {url:"$A/modules/adverse-event-data.html",Table:"local-sleep-adverse-event",form_module:"local-sleep-adverse-event-form"},
        "local-sleep-adverse-event-form":                {url:"$A/modules/adverse-event-form.html",Table:"local-sleep-adverse-event"},

        "local-sleep-s-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-s-date",form_module:"local-sleep-s-date-form"},
        "local-sleep-s-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-s-date"},
        "local-sleep-b-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-b-d1-date",form_module:"local-sleep-b-d1-date-form"},
        "local-sleep-b-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-b-d1-date"},
        "local-sleep-b-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-b-d2-date",form_module:"local-sleep-b-d2-date-form"},
        "local-sleep-b-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-b-d2-date"},
        "local-sleep-b-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-b-d3-date",form_module:"local-sleep-b-d3-date-form"},
        "local-sleep-b-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-b-d3-date"},
        "local-sleep-t1-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d1-date",form_module:"local-sleep-t1-d1-date-form"},
        "local-sleep-t1-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d1-date"},
        "local-sleep-t1-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d2-date",form_module:"local-sleep-t1-d2-date-form"},
        "local-sleep-t1-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d2-date"},
        "local-sleep-t1-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d3-date",form_module:"local-sleep-t1-d3-date-form"},
        "local-sleep-t1-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d3-date"},
        "local-sleep-t1-d4-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d4-date",form_module:"local-sleep-t1-d4-date-form"},
        "local-sleep-t1-d4-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d4-date"},
        "local-sleep-t1-d5-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d5-date",form_module:"local-sleep-t1-d5-date-form"},
        "local-sleep-t1-d5-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d5-date"},
        "local-sleep-t2-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d1-date",form_module:"local-sleep-t2-d1-date-form"},
        "local-sleep-t2-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d1-date"},
        "local-sleep-t2-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d2-date",form_module:"local-sleep-t2-d2-date-form"},
        "local-sleep-t2-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d2-date"},
        "local-sleep-t2-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d3-date",form_module:"local-sleep-t2-d3-date-form"},
        "local-sleep-t2-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d3-date"},
        "local-sleep-t2-d4-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d4-date",form_module:"local-sleep-t2-d4-date-form"},
        "local-sleep-t2-d4-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d4-date"},
        "local-sleep-t2-d5-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d5-date",form_module:"local-sleep-t2-d5-date-form"},
        "local-sleep-t2-d5-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d5-date"},
        "local-sleep-6m-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-6m-date",form_module:"local-sleep-6m-date-form"},
        "local-sleep-6m-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-6m-date"},
        "local-sleep-fu-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d1-date",form_module:"local-sleep-fu-d1-date-form"},
        "local-sleep-fu-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d1-date"},
        "local-sleep-fu-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d2-date",form_module:"local-sleep-fu-d2-date-form"},
        "local-sleep-fu-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d2-date"},
        "local-sleep-fu-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d3-date",form_module:"local-sleep-fu-d3-date-form"},
        "local-sleep-fu-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d3-date"},

        "local-sleep-s-ethnicity-data":		                        {url:"$A/modules/ethnicity-data.html",Table:"local-sleep-s-ethnicity",form_module:"local-sleep-s-ethnicity-form"},
        "local-sleep-s-ethnicity-form":		                {url:"$A/modules/ethnicity-form.html",Table:"local-sleep-s-ethnicity"},
        "local-sleep-s-lifestyle-data":		                        {url:"$A/modules/lifestyle-data.html",Table:"local-sleep-s-lifestyle",form_module:"local-sleep-s-lifestyle-form"},
        "local-sleep-s-lifestyle-form":		                {url:"$A/modules/lifestyle-form.html",Table:"local-sleep-s-lifestyle"},
        "local-sleep-s-education-data":		                        {url:"$A/modules/education-data.html",Table:"local-sleep-s-education",form_module:"local-sleep-s-education-form"},
        "local-sleep-s-education-form":		                {url:"$A/modules/education-form.html",Table:"local-sleep-s-education"},
        "local-sleep-s-medications-data":		                        {url:"$A/modules/medications-data.html",Table:"local-sleep-s-medications",form_module:"local-sleep-s-medications-form"},
        "local-sleep-s-medications-form":		                {url:"$A/modules/medications-form.html",Table:"local-sleep-s-medications"},
        "local-sleep-s-medical-history-data":		                        {url:"$A/modules/medical-history-data.html",Table:"local-sleep-s-medical-history",form_module:"local-sleep-s-medical-history-form"},
        "local-sleep-s-medical-history-form":		                {url:"$A/modules/medical-history-form.html",Table:"local-sleep-s-medical-history"},
        "local-sleep-s-ess-data":		                        {url:"$A/modules/ess-data.html",Table:"local-sleep-s-ess",form_module:"local-sleep-s-ess-form"},
        "local-sleep-s-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-s-ess"},
        "local-sleep-s-dass-data":		                        {url:"$A/modules/dass-data.html",Table:"local-sleep-s-dass",form_module:"local-sleep-s-dass-form"},
        "local-sleep-s-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-s-dass"},
        "local-sleep-s-mva-data":		                        {url:"$A/modules/mva-data.html",Table:"local-sleep-s-mva",form_module:"local-sleep-s-mva-form"},
        "local-sleep-s-mva-form":		                {url:"$A/modules/mva-form.html",Table:"local-sleep-s-mva"},
        "local-sleep-s-aused-data":		                        {url:"$A/modules/aused-data.html",Table:"local-sleep-s-aused",form_module:"local-sleep-s-aused-form"},
        "local-sleep-s-aused-form":		                {url:"$A/modules/aused-form.html",Table:"local-sleep-s-aused"},

        "local-sleep-b-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d1-anthropometry-short",form_module:"local-sleep-b-d1-anthropometry-short-form"},
        "local-sleep-b-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d1-anthropometry-short"},
        "local-sleep-b-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-b-d1-ess",form_module:"local-sleep-b-d1-ess-form"},
        "local-sleep-b-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-b-d1-ess"},
        "local-sleep-b-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-b-d1-dass",form_module:"local-sleep-b-d1-dass-form"},
        "local-sleep-b-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-b-d1-dass"},
        "local-sleep-b-d1-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-b-d1-cpap-upload",form_module:"local-sleep-b-d1-cpap-upload-form"},
        "local-sleep-b-d1-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-b-d1-cpap-upload"},
        "local-sleep-b-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-b-d1-cpap",form_module:"local-sleep-b-d1-cpap-form"},
        "local-sleep-b-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-b-d1-cpap"},

        "local-sleep-b-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d2-anthropometry-short",form_module:"local-sleep-b-d2-anthropometry-short-form"},
        "local-sleep-b-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d2-anthropometry-short"},
        "local-sleep-b-d2-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-b-d2-cpap-upload",form_module:"local-sleep-b-d2-cpap-upload-form"},
        "local-sleep-b-d2-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-b-d2-cpap-upload"},
        "local-sleep-b-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-b-d2-cpap",form_module:"local-sleep-b-d2-cpap-form"},
        "local-sleep-b-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-b-d2-cpap"},

        "local-sleep-b-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d3-anthropometry-short",form_module:"local-sleep-b-d3-anthropometry-short-form"},
        "local-sleep-b-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d3-anthropometry-short"},

        "local-sleep-t1-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d1-anthropometry-short",form_module:"local-sleep-t1-d1-anthropometry-short-form"},
        "local-sleep-t1-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d1-anthropometry-short"},
        "local-sleep-t1-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-t1-d1-ess",form_module:"local-sleep-t1-d1-ess-form"},
        "local-sleep-t1-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-t1-d1-ess"},
        "local-sleep-t1-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-t1-d1-dass",form_module:"local-sleep-t1-d1-dass-form"},
        "local-sleep-t1-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-t1-d1-dass"},
        "local-sleep-t1-d1-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t1-d1-cpap-upload",form_module:"local-sleep-t1-d1-cpap-upload-form"},
        "local-sleep-t1-d1-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t1-d1-cpap-upload"},
        "local-sleep-t1-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d1-cpap",form_module:"local-sleep-t1-d1-cpap-form"},
        "local-sleep-t1-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d1-cpap"},

        "local-sleep-t1-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d2-anthropometry-short",form_module:"local-sleep-t1-d2-anthropometry-short-form"},
        "local-sleep-t1-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d2-anthropometry-short"},
        "local-sleep-t1-d2-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t1-d2-cpap-upload",form_module:"local-sleep-t1-d2-cpap-upload-form"},
        "local-sleep-t1-d2-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t1-d2-cpap-upload"},
        "local-sleep-t1-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d2-cpap",form_module:"local-sleep-t1-d2-cpap-form"},
        "local-sleep-t1-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d2-cpap"},

        "local-sleep-t1-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d3-anthropometry-short",form_module:"local-sleep-t1-d3-anthropometry-short-form"},
        "local-sleep-t1-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d3-anthropometry-short"},
        "local-sleep-t1-d3-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t1-d3-cpap-upload",form_module:"local-sleep-t1-d3-cpap-upload-form"},
        "local-sleep-t1-d3-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t1-d3-cpap-upload"},
        "local-sleep-t1-d3-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d3-cpap",form_module:"local-sleep-t1-d3-cpap-form"},
        "local-sleep-t1-d3-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d3-cpap"},

        "local-sleep-t1-d4-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d4-anthropometry-short",form_module:"local-sleep-t1-d4-anthropometry-short-form"},
        "local-sleep-t1-d4-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d4-anthropometry-short"},
        "local-sleep-t1-d4-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t1-d4-cpap-upload",form_module:"local-sleep-t1-d4-cpap-upload-form"},
        "local-sleep-t1-d4-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t1-d4-cpap-upload"},
        "local-sleep-t1-d4-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d4-cpap",form_module:"local-sleep-t1-d4-cpap-form"},
        "local-sleep-t1-d4-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d4-cpap"},

        "local-sleep-t1-d5-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d5-anthropometry-short",form_module:"local-sleep-t1-d5-anthropometry-short-form"},
        "local-sleep-t1-d5-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d5-anthropometry-short"},

        "local-sleep-t2-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d1-anthropometry-short",form_module:"local-sleep-t2-d1-anthropometry-short-form"},
        "local-sleep-t2-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d1-anthropometry-short"},
        "local-sleep-t2-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-t2-d1-ess",form_module:"local-sleep-t2-d1-ess-form"},
        "local-sleep-t2-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-t2-d1-ess"},
        "local-sleep-t2-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-t2-d1-dass",form_module:"local-sleep-t2-d1-dass-form"},
        "local-sleep-t2-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-t2-d1-dass"},
        "local-sleep-t2-d1-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t2-d1-cpap-upload",form_module:"local-sleep-t2-d1-cpap-upload-form"},
        "local-sleep-t2-d1-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t2-d1-cpap-upload"},
        "local-sleep-t2-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d1-cpap",form_module:"local-sleep-t2-d1-cpap-form"},
        "local-sleep-t2-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d1-cpap"},

        "local-sleep-t2-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d2-anthropometry-short",form_module:"local-sleep-t2-d2-anthropometry-short-form"},
        "local-sleep-t2-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d2-anthropometry-short"},
        "local-sleep-t2-d2-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t2-d2-cpap-upload",form_module:"local-sleep-t2-d2-cpap-upload-form"},
        "local-sleep-t2-d2-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t2-d2-cpap-upload"},
        "local-sleep-t2-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d2-cpap",form_module:"local-sleep-t2-d2-cpap-form"},
        "local-sleep-t2-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d2-cpap"},

        "local-sleep-t2-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d3-anthropometry-short",form_module:"local-sleep-t2-d3-anthropometry-short-form"},
        "local-sleep-t2-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d3-anthropometry-short"},
        "local-sleep-t2-d3-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t2-d3-cpap-upload",form_module:"local-sleep-t2-d3-cpap-upload-form"},
        "local-sleep-t2-d3-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t2-d3-cpap-upload"},
        "local-sleep-t2-d3-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d3-cpap",form_module:"local-sleep-t2-d3-cpap-form"},
        "local-sleep-t2-d3-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d3-cpap"},

        "local-sleep-t2-d4-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d4-anthropometry-short",form_module:"local-sleep-t2-d4-anthropometry-short-form"},
        "local-sleep-t2-d4-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d4-anthropometry-short"},
        "local-sleep-t2-d4-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-t2-d4-cpap-upload",form_module:"local-sleep-t2-d4-cpap-upload-form"},
        "local-sleep-t2-d4-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-t2-d4-cpap-upload"},
        "local-sleep-t2-d4-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d4-cpap",form_module:"local-sleep-t2-d4-cpap-form"},
        "local-sleep-t2-d4-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d4-cpap"},

        "local-sleep-t2-d5-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d5-anthropometry-short",form_module:"local-sleep-t2-d5-anthropometry-short-form"},
        "local-sleep-t2-d5-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d5-anthropometry-short"},

        "local-sleep-fu-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d1-anthropometry-short",form_module:"local-sleep-fu-d1-anthropometry-short-form"},
        "local-sleep-fu-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d1-anthropometry-short"},
        "local-sleep-fu-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-fu-d1-ess",form_module:"local-sleep-fu-d1-ess-form"},
        "local-sleep-fu-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-fu-d1-ess"},
        "local-sleep-fu-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-fu-d1-dass",form_module:"local-sleep-fu-d1-dass-form"},
        "local-sleep-fu-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-fu-d1-dass"},
        "local-sleep-fu-d1-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-fu-d1-cpap-upload",form_module:"local-sleep-fu-d1-cpap-upload-form"},
        "local-sleep-fu-d1-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-fu-d1-cpap-upload"},
        "local-sleep-fu-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-fu-d1-cpap",form_module:"local-sleep-fu-d1-cpap-form"},
        "local-sleep-fu-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-fu-d1-cpap"},

        "local-sleep-fu-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d2-anthropometry-short",form_module:"local-sleep-fu-d2-anthropometry-short-form"},
        "local-sleep-fu-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d2-anthropometry-short"},
        "local-sleep-fu-d2-cpap-upload-data":		                {url:"$A/modules/cpap-upload-data.html",Table:"local-sleep-fu-d2-cpap-upload",form_module:"local-sleep-fu-d2-cpap-upload-form"},
        "local-sleep-fu-d2-cpap-upload-form":		                {url:"$A/modules/cpap-upload-form.html",Table:"local-sleep-fu-d2-cpap-upload"},
        "local-sleep-fu-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-fu-d2-cpap",form_module:"local-sleep-fu-d2-cpap-form"},
        "local-sleep-fu-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-fu-d2-cpap"},

        "local-sleep-fu-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d3-anthropometry-short",form_module:"local-sleep-fu-d3-anthropometry-short-form"},
        "local-sleep-fu-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d3-anthropometry-short"},

    }
    for(m in modules){$vm.module_list[m]=modules[m];}
})();
