(function(){
    var modules={
        "panel-main-local-sleep":    			{url:"$A/components/panel/panel-main.html",router:1},
        "panel-child-local-sleep":    			{url:"$A/components/panel/panel-child.html"},
        
        "participant-data":   		{url:"$A/components/participant/participant-data.html",Table:"local-sleep-participant",form_module:"participant-form",router:1,
                                            child_panel:"panel-child-local-sleep",
                                            questionnaire_setup:"online-questionnaire-setup-local-sleep",
                                            online_questionnaire:"online-questionnaire-app-local-sleep",
                                            participant_id:{field1:"Subject_ID",field2:"Subject_Initials"}
                                        },
        "participant-form":   		{url:"$A/components/participant/participant-form.html",Table:"local-sleep-participant"},

        "online-questionnaire-setup-local-sleep": 	{url:"$A/online-questionnaire/components/online-questionnaire-setup.html",Table:"local-sleep-participant"},
        "online-questionnaire-app-local-sleep":    {url:"$A/online-questionnaire/index.html"},

        "notes":  		  	  			{url:"$A/modules/notes.html"},

        "local-sleep-randomisation-table-data":		    {url:"$A/modules/randomisation-table-data.html",Table:"local-sleep-randomisation-table",form_module:"local-sleep-randomisation-table-form"},
        "local-sleep-randomisation-table-form":		    {url:"$A/modules/randomisation-table-form.html",Table:"local-sleep-randomisation-table"},
        "local-sleep-concom-medication-data":            {url:"$A/modules/concom-medication-data.html",Table:"local-sleep-concom-medication",form_module:"local-sleep-concom-medication-form"},
        "local-sleep-concom-medication-form":            {url:"$A/modules/concom-medication-form.html",Table:"local-sleep-concom-medication"},
        "local-sleep-g-adverse-event-data":                {url:"$A/modules/adverse-event-data.html",Table:"local-sleep-g-adverse-event",form_module:"local-sleep-g-adverse-event-form"},
        "local-sleep-g-adverse-event-form":                {url:"$A/modules/adverse-event-form.html",Table:"local-sleep-g-adverse-event"},
        "local-sleep-g-protocol-amendments-data":                {url:"$A/modules/protocol-amendments-data.html",Table:"local-sleep-g-protocol-amendments",form_module:"local-sleep-g-protocol-amendments-form"},
        "local-sleep-g-protocol-amendments-form":                {url:"$A/modules/protocol-amendments-form.html",Table:"local-sleep-g-protocol-amendments"},

        "local-sleep-s-date-data":		                    {url:"$A/modules/date-data.html",Table:"local-sleep-s-date",form_module:"local-sleep-s-date-form"},
        "local-sleep-s-date-form":		                    {url:"$A/modules/date-form.html",Table:"local-sleep-s-date"},
        "local-sleep-b-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-b-d1-date",form_module:"local-sleep-b-d1-date-form"},
        "local-sleep-b-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-b-d1-date"},
        "local-sleep-b-d2-bl-date-data":		            {url:"$A/modules/date-data.html",Table:"local-sleep-b-d2-bl-date",form_module:"local-sleep-b-d2-bl-date-form"},
        "local-sleep-b-d2-bl-date-form":		            {url:"$A/modules/date-form.html",Table:"local-sleep-b-d2-bl-date"},
        "local-sleep-b-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-b-d3-date",form_module:"local-sleep-b-d3-date-form"},
        "local-sleep-b-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-b-d3-date"},
        "local-sleep-t1-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d1-date",form_module:"local-sleep-t1-d1-date-form"},
        "local-sleep-t1-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d1-date"},
        "local-sleep-t1-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d2-date",form_module:"local-sleep-t1-d2-date-form"},
        "local-sleep-t1-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d2-date"},
        "local-sleep-t1-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d3-date",form_module:"local-sleep-t1-d3-date-form"},
        "local-sleep-t1-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d3-date"},
        "local-sleep-t1-d4-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d4-date",form_module:"local-sleep-t1-d4-date-form"},
        "local-sleep-t1-d4-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d4-date"},
        "local-sleep-t1-d5-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t1-d5-date",form_module:"local-sleep-t1-d5-date-form"},
        "local-sleep-t1-d5-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t1-d5-date"},
        "local-sleep-t2-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d1-date",form_module:"local-sleep-t2-d1-date-form"},
        "local-sleep-t2-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d1-date"},
        "local-sleep-t2-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d2-date",form_module:"local-sleep-t2-d2-date-form"},
        "local-sleep-t2-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d2-date"},
        "local-sleep-t2-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d3-date",form_module:"local-sleep-t2-d3-date-form"},
        "local-sleep-t2-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d3-date"},
        "local-sleep-t2-d4-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d4-date",form_module:"local-sleep-t2-d4-date-form"},
        "local-sleep-t2-d4-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d4-date"},
        "local-sleep-t2-d5-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-t2-d5-date",form_module:"local-sleep-t2-d5-date-form"},
        "local-sleep-t2-d5-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-t2-d5-date"},

        "local-sleep-6m-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-6m-date",form_module:"local-sleep-6m-date-form"},
        "local-sleep-6m-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-6m-date"},
        "local-sleep-6m-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-6m-cpap-upload",form_module:"local-sleep-6m-cpap-upload-form"},
        "local-sleep-6m-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-6m-cpap-upload"},
        "local-sleep-6m-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-6m-cpap",form_module:"local-sleep-6m-cpap-form"},
        "local-sleep-6m-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-6m-cpap"},

        "local-sleep-fu-d1-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d1-date",form_module:"local-sleep-fu-d1-date-form"},
        "local-sleep-fu-d1-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d1-date"},
        "local-sleep-fu-d2-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d2-date",form_module:"local-sleep-fu-d2-date-form"},
        "local-sleep-fu-d2-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d2-date"},
        "local-sleep-fu-d3-date-data":		                {url:"$A/modules/date-data.html",Table:"local-sleep-fu-d3-date",form_module:"local-sleep-fu-d3-date-form"},
        "local-sleep-fu-d3-date-form":		                {url:"$A/modules/date-form.html",Table:"local-sleep-fu-d3-date"},

        "local-sleep-s-inclusion-exclusion-data":           {url:"$A/modules/inclusion-exclusion-data.html",Table:"local-sleep-s-inclusion-exclusion",form_module:"local-sleep-s-inclusion-exclusion-form"},
        "local-sleep-s-inclusion-exclusion-form":           {url:"$A/modules/inclusion-exclusion-form.html",Table:"local-sleep-s-inclusion-exclusion",task_name:"Inclusion/Exclusion Criteria"},
        "local-sleep-s-concom-file-data":		                    {url:"$A/modules/upload-file-data.html",Table:"local-sleep-s-concom-file",form_module:"local-sleep-s-concom-file-form"},
        "local-sleep-s-concom-file-form":		                    {url:"$A/modules/upload-file-form.html",Table:"local-sleep-s-concom-file"},
        "local-sleep-s-medications-data":		                        {url:"$A/modules/medications-data.html",Table:"local-sleep-s-medications",form_module:"local-sleep-s-medications-form"},
        "local-sleep-s-medications-form":		                {url:"$A/modules/medications-form.html",Table:"local-sleep-s-medications",task_name:"Concomitant medication"},
        "local-sleep-s-medical-history-data":		                        {url:"$A/modules/medical-history-data.html",Table:"local-sleep-s-medical-history",form_module:"local-sleep-s-medical-history-form"},
        "local-sleep-s-medical-history-form":		                {url:"$A/modules/medical-history-form.html",Table:"local-sleep-s-medical-history",task_name:"Medical history"},
        "local-sleep-s-ess-data":		                        {url:"$A/modules/ess-data.html",Table:"local-sleep-s-ess",form_module:"local-sleep-s-ess-form"},
        "local-sleep-s-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-s-ess",task_name:"ESS"},
        "local-sleep-s-mva-data":		                        {url:"$A/modules/mva-data.html",Table:"local-sleep-s-mva",form_module:"local-sleep-s-mva-form"},
        "local-sleep-s-mva-form":		                {url:"$A/modules/mva-form.html",Table:"local-sleep-s-mva",task_name:"MVA"},
        "local-sleep-s-aused-60-data":		                        {url:"$A/modules/aused-60-data.html",Table:"local-sleep-s-aused-60",form_module:"local-sleep-s-aused-60-form"},
        "local-sleep-s-aused-60-form":		                {url:"$A/modules/aused-60-form.html",Table:"local-sleep-s-aused-60"},
        "local-sleep-s-anthropometry-data":		                        {url:"$A/modules/anthropometry-data.html",Table:"local-sleep-s-anthropometry",form_module:"local-sleep-s-anthropometry-form"},
        "local-sleep-s-anthropometry-form":		                {url:"$A/modules/anthropometry-form.html",Table:"local-sleep-s-anthropometry"},
        "local-sleep-s-sleep-diary-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-s-sleep-diary",form_module:"local-sleep-s-sleep-diary-form"},
        "local-sleep-s-sleep-diary-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-s-sleep-diary"},
        "local-sleep-s-psg-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-s-psg-upload",form_module:"local-sleep-s-psg-upload-form"},
        "local-sleep-s-psg-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-s-psg-upload"},
        "local-sleep-s-source-doc-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-s-source-doc",form_module:"local-sleep-s-source-doc-form"},
        "local-sleep-s-source-doc-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-s-source-doc"},

        "local-sleep-b-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d1-anthropometry-short",form_module:"local-sleep-b-d1-anthropometry-short-form"},
        "local-sleep-b-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d1-anthropometry-short"},
        "local-sleep-b-ethnicity-data":		                        {url:"$A/modules/ethnicity-data.html",Table:"local-sleep-b-ethnicity",form_module:"local-sleep-b-ethnicity-form"},
        "local-sleep-b-ethnicity-form":		                {url:"$A/modules/ethnicity-form.html",Table:"local-sleep-b-ethnicity",task_name:"Ethnicity"},
        "local-sleep-b-lifestyle-data":		                        {url:"$A/modules/lifestyle-data.html",Table:"local-sleep-b-lifestyle",form_module:"local-sleep-b-lifestyle-form"},
        "local-sleep-b-lifestyle-form":		                {url:"$A/modules/lifestyle-form.html",Table:"local-sleep-b-lifestyle",task_name:"Lifestyle"},
        "local-sleep-b-education-data":		                        {url:"$A/modules/education-data.html",Table:"local-sleep-b-education",form_module:"local-sleep-b-education-form"},
        "local-sleep-b-education-form":		                {url:"$A/modules/education-form.html",Table:"local-sleep-b-education",task_name:"Education"},
        "local-sleep-b-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-b-d1-ess",form_module:"local-sleep-b-d1-ess-form"},
        "local-sleep-b-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-b-d1-ess",task_name:"ESS"},
        "local-sleep-b-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-b-d1-dass",form_module:"local-sleep-b-d1-dass-form"},
        "local-sleep-b-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-b-d1-dass",task_name:"DASS"},
        "local-sleep-b-d1-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-d1-cpap-upload",form_module:"local-sleep-b-d1-cpap-upload-form"},
        "local-sleep-b-d1-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-d1-cpap-upload"},
        "local-sleep-b-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-b-d1-cpap",form_module:"local-sleep-b-d1-cpap-form"},
        "local-sleep-b-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-b-d1-cpap"},

        "local-sleep-b-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d2-anthropometry-short",form_module:"local-sleep-b-d2-anthropometry-short-form"},
        "local-sleep-b-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d2-anthropometry-short"},
        "local-sleep-b-d2-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-d2-cpap-upload",form_module:"local-sleep-b-d2-cpap-upload-form"},
        "local-sleep-b-d2-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-d2-cpap-upload"},
        "local-sleep-b-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-b-d2-cpap",form_module:"local-sleep-b-d2-cpap-form"},
        "local-sleep-b-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-b-d2-cpap"},

        "local-sleep-b-d2-bla-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-bla-kss",form_module:"local-sleep-b-d2-bla-kss-form"},
        "local-sleep-b-d2-bla-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-bl-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d2-bl-pvt",form_module:"local-sleep-b-d2-bl-pvt-form"},
        "local-sleep-b-d2-bl-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d2-bl-pvt"},
        "local-sleep-b-d2-blb-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-blb-kss",form_module:"local-sleep-b-d2-blb-kss-form"},
        "local-sleep-b-d2-blb-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t1a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t1a-kss",form_module:"local-sleep-b-d2-t1a-kss-form"},
        "local-sleep-b-d2-t1a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t1-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d2-t1-pvt",form_module:"local-sleep-b-d2-t1-pvt-form"},
        "local-sleep-b-d2-t1-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d2-t1-pvt"},
        "local-sleep-b-d2-t1b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t1b-kss",form_module:"local-sleep-b-d2-t1b-kss-form"},
        "local-sleep-b-d2-t1b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t2a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t2a-kss",form_module:"local-sleep-b-d2-t2a-kss-form"},
        "local-sleep-b-d2-t2a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t2-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d2-t2-pvt",form_module:"local-sleep-b-d2-t2-pvt-form"},
        "local-sleep-b-d2-t2-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d2-t2-pvt"},
        "local-sleep-b-d2-t2b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t2b-kss",form_module:"local-sleep-b-d2-t2b-kss-form"},
        "local-sleep-b-d2-t2b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t3a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t3a-kss",form_module:"local-sleep-b-d2-t3a-kss-form"},
        "local-sleep-b-d2-t3a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t3-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d2-t3-pvt",form_module:"local-sleep-b-d2-t3-pvt-form"},
        "local-sleep-b-d2-t3-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d2-t3-pvt"},
        "local-sleep-b-d2-t3b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t3b-kss",form_module:"local-sleep-b-d2-t3b-kss-form"},
        "local-sleep-b-d2-t3b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d2-t4a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t4a-kss",form_module:"local-sleep-b-d2-t4a-kss-form"},
        "local-sleep-b-d2-t4a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d2-t4-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d2-t4-pvt",form_module:"local-sleep-b-d2-t4-pvt-form"},
        "local-sleep-b-d2-t4-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d2-t4-pvt"},
        "local-sleep-b-d2-t4b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d2-t4b-kss",form_module:"local-sleep-b-d2-t4b-kss-form"},
        "local-sleep-b-d2-t4b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d2-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d3-t5a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d3-t5a-kss",form_module:"local-sleep-b-d3-t5a-kss-form"},
        "local-sleep-b-d3-t5a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d3-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-b-d3-t5-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-b-d3-t5-pvt",form_module:"local-sleep-b-d3-t5-pvt-form"},
        "local-sleep-b-d3-t5-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-b-d3-t5-pvt"},
        "local-sleep-b-d3-t5b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-b-d3-t5b-kss",form_module:"local-sleep-b-d3-t5b-kss-form"},
        "local-sleep-b-d3-t5b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-b-d3-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-b-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-b-d3-anthropometry-short",form_module:"local-sleep-b-d3-anthropometry-short-form"},
        "local-sleep-b-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-b-d3-anthropometry-short"},

        "local-sleep-b-g1-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-b-g1-psg300",form_module:"local-sleep-b-g1-psg300-form"},
        "local-sleep-b-g1-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-b-g1-psg300"},
        "local-sleep-b-g2-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-b-g2-psg300",form_module:"local-sleep-b-g2-psg300-form"},
        "local-sleep-b-g2-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-b-g2-psg300"},
        "local-sleep-b-g1-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g1-psgedf",form_module:"local-sleep-b-g1-psgedf-form"},
        "local-sleep-b-g1-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g1-psgedf"},
        "local-sleep-b-g2-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g2-psgedf",form_module:"local-sleep-b-g2-psgedf-form"},
        "local-sleep-b-g2-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g2-psgedf"},
        "local-sleep-b-g1-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g1-sleep-scoring",form_module:"local-sleep-b-g1-sleep-scoring-form"},
        "local-sleep-b-g1-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g1-sleep-scoring"},
        "local-sleep-b-g2-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g2-sleep-scoring",form_module:"local-sleep-b-g2-sleep-scoring-form"},
        "local-sleep-b-g2-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g2-sleep-scoring"},
        "local-sleep-b-g-source-doc-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g-source-doc",form_module:"local-sleep-b-g-source-doc-form"},
        "local-sleep-b-g-source-doc-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g-source-doc"},
        "local-sleep-b-g-sleep-diary-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g-sleep-diary",form_module:"local-sleep-b-g-sleep-diary-form"},
        "local-sleep-b-g-sleep-diary-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g-sleep-diary"},
        "local-sleep-b-g-finapres-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g-finapres",form_module:"local-sleep-b-g-finapres-form"},
        "local-sleep-b-g-finapres-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g-finapres"},
        "local-sleep-b-g-geoscan-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-b-g-geoscan",form_module:"local-sleep-b-g-geoscan-form"},
        "local-sleep-b-g-geoscan-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-b-g-geoscan"},

        "local-sleep-t1-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d1-anthropometry-short",form_module:"local-sleep-t1-d1-anthropometry-short-form"},
        "local-sleep-t1-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d1-anthropometry-short"},
        "local-sleep-t1-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-t1-d1-ess",form_module:"local-sleep-t1-d1-ess-form"},
        "local-sleep-t1-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-t1-d1-ess",task_name:"ESS"},
        "local-sleep-t1-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-t1-d1-dass",form_module:"local-sleep-t1-d1-dass-form"},
        "local-sleep-t1-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-t1-d1-dass",task_name:"DASS"},
        "local-sleep-t1-d1-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-d1-cpap-upload",form_module:"local-sleep-t1-d1-cpap-upload-form"},
        "local-sleep-t1-d1-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-d1-cpap-upload"},
        "local-sleep-t1-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d1-cpap",form_module:"local-sleep-t1-d1-cpap-form"},
        "local-sleep-t1-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d1-cpap"},

        "local-sleep-t1-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d2-anthropometry-short",form_module:"local-sleep-t1-d2-anthropometry-short-form"},
        "local-sleep-t1-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d2-anthropometry-short"},
        "local-sleep-t1-d2-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-d2-cpap-upload",form_module:"local-sleep-t1-d2-cpap-upload-form"},
        "local-sleep-t1-d2-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-d2-cpap-upload"},
        "local-sleep-t1-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d2-cpap",form_module:"local-sleep-t1-d2-cpap-form"},
        "local-sleep-t1-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d2-cpap"},

        "local-sleep-t1-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d3-anthropometry-short",form_module:"local-sleep-t1-d3-anthropometry-short-form"},
        "local-sleep-t1-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d3-anthropometry-short"},
        "local-sleep-t1-d3-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-d3-cpap-upload",form_module:"local-sleep-t1-d3-cpap-upload-form"},
        "local-sleep-t1-d3-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-d3-cpap-upload"},
        "local-sleep-t1-d3-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d3-cpap",form_module:"local-sleep-t1-d3-cpap-form"},
        "local-sleep-t1-d3-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d3-cpap"},

        "local-sleep-t1-d4-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d4-anthropometry-short",form_module:"local-sleep-t1-d4-anthropometry-short-form"},
        "local-sleep-t1-d4-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d4-anthropometry-short"},
        "local-sleep-t1-d4-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-d4-cpap-upload",form_module:"local-sleep-t1-d4-cpap-upload-form"},
        "local-sleep-t1-d4-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-d4-cpap-upload"},
        "local-sleep-t1-d4-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t1-d4-cpap",form_module:"local-sleep-t1-d4-cpap-form"},
        "local-sleep-t1-d4-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t1-d4-cpap"},

        "local-sleep-t1-d4-bla-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-bla-kss",form_module:"local-sleep-t1-d4-bla-kss-form"},
        "local-sleep-t1-d4-bla-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-bl-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d4-bl-pvt",form_module:"local-sleep-t1-d4-bl-pvt-form"},
        "local-sleep-t1-d4-bl-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d4-bl-pvt"},
        "local-sleep-t1-d4-blb-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-blb-kss",form_module:"local-sleep-t1-d4-blb-kss-form"},
        "local-sleep-t1-d4-blb-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t1a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t1a-kss",form_module:"local-sleep-t1-d4-t1a-kss-form"},
        "local-sleep-t1-d4-t1a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t1-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d4-t1-pvt",form_module:"local-sleep-t1-d4-t1-pvt-form"},
        "local-sleep-t1-d4-t1-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d4-t1-pvt"},
        "local-sleep-t1-d4-t1b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t1b-kss",form_module:"local-sleep-t1-d4-t1b-kss-form"},
        "local-sleep-t1-d4-t1b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t2a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t2a-kss",form_module:"local-sleep-t1-d4-t2a-kss-form"},
        "local-sleep-t1-d4-t2a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t2-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d4-t2-pvt",form_module:"local-sleep-t1-d4-t2-pvt-form"},
        "local-sleep-t1-d4-t2-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d4-t2-pvt"},
        "local-sleep-t1-d4-t2b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t2b-kss",form_module:"local-sleep-t1-d4-t2b-kss-form"},
        "local-sleep-t1-d4-t2b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t3a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t3a-kss",form_module:"local-sleep-t1-d4-t3a-kss-form"},
        "local-sleep-t1-d4-t3a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t3-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d4-t3-pvt",form_module:"local-sleep-t1-d4-t3-pvt-form"},
        "local-sleep-t1-d4-t3-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d4-t3-pvt"},
        "local-sleep-t1-d4-t3b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t3b-kss",form_module:"local-sleep-t1-d4-t3b-kss-form"},
        "local-sleep-t1-d4-t3b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d4-t4a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t4a-kss",form_module:"local-sleep-t1-d4-t4a-kss-form"},
        "local-sleep-t1-d4-t4a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d4-t4-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d4-t4-pvt",form_module:"local-sleep-t1-d4-t4-pvt-form"},
        "local-sleep-t1-d4-t4-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d4-t4-pvt"},
        "local-sleep-t1-d4-t4b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d4-t4b-kss",form_module:"local-sleep-t1-d4-t4b-kss-form"},
        "local-sleep-t1-d4-t4b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d4-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d5-t5a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d5-t5a-kss",form_module:"local-sleep-t1-d5-t5a-kss-form"},
        "local-sleep-t1-d5-t5a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d5-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t1-d5-t5-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t1-d5-t5-pvt",form_module:"local-sleep-t1-d5-t5-pvt-form"},
        "local-sleep-t1-d5-t5-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t1-d5-t5-pvt"},
        "local-sleep-t1-d5-t5b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t1-d5-t5b-kss",form_module:"local-sleep-t1-d5-t5b-kss-form"},
        "local-sleep-t1-d5-t5b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t1-d5-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-t1-d5-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t1-d5-anthropometry-short",form_module:"local-sleep-t1-d5-anthropometry-short-form"},
        "local-sleep-t1-d5-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t1-d5-anthropometry-short"},
 
        "local-sleep-t1-g1-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-t1-g1-psg300",form_module:"local-sleep-t1-g1-psg300-form"},
        "local-sleep-t1-g1-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-t1-g1-psg300"},
        "local-sleep-t1-g2-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-t1-g2-psg300",form_module:"local-sleep-t1-g2-psg300-form"},
        "local-sleep-t1-g2-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-t1-g2-psg300"},
        "local-sleep-t1-g1-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g1-psgedf",form_module:"local-sleep-t1-g1-psgedf-form"},
        "local-sleep-t1-g1-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g1-psgedf"},
        "local-sleep-t1-g2-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g2-psgedf",form_module:"local-sleep-t1-g2-psgedf-form"},
        "local-sleep-t1-g2-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g2-psgedf"},
        "local-sleep-t1-g1-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g1-sleep-scoring",form_module:"local-sleep-t1-g1-sleep-scoring-form"},
        "local-sleep-t1-g1-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g1-sleep-scoring"},
        "local-sleep-t1-g2-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g2-sleep-scoring",form_module:"local-sleep-t1-g2-sleep-scoring-form"},
        "local-sleep-t1-g2-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g2-sleep-scoring"},
        "local-sleep-t1-g-source-doc-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g-source-doc",form_module:"local-sleep-t1-g-source-doc-form"},
        "local-sleep-t1-g-source-doc-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g-source-doc"},
        "local-sleep-t1-g-sleep-diary-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g-sleep-diary",form_module:"local-sleep-t1-g-sleep-diary-form"},
        "local-sleep-t1-g-sleep-diary-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g-sleep-diary"},
        "local-sleep-t1-g-finapres-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g-finapres",form_module:"local-sleep-t1-g-finapres-form"},
        "local-sleep-t1-g-finapres-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g-finapres"},
        "local-sleep-t1-g-geoscan-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t1-g-geoscan",form_module:"local-sleep-t1-g-geoscan-form"},
        "local-sleep-t1-g-geoscan-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t1-g-geoscan"},

        "local-sleep-t2-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d1-anthropometry-short",form_module:"local-sleep-t2-d1-anthropometry-short-form"},
        "local-sleep-t2-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d1-anthropometry-short"},
        "local-sleep-t2-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-t2-d1-ess",form_module:"local-sleep-t2-d1-ess-form"},
        "local-sleep-t2-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-t2-d1-ess",task_name:"ESS"},
        "local-sleep-t2-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-t2-d1-dass",form_module:"local-sleep-t2-d1-dass-form"},
        "local-sleep-t2-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-t2-d1-dass",task_name:"DASS"},
        "local-sleep-t2-d1-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-d1-cpap-upload",form_module:"local-sleep-t2-d1-cpap-upload-form"},
        "local-sleep-t2-d1-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-d1-cpap-upload"},
        "local-sleep-t2-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d1-cpap",form_module:"local-sleep-t2-d1-cpap-form"},
        "local-sleep-t2-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d1-cpap"},

        "local-sleep-t2-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d2-anthropometry-short",form_module:"local-sleep-t2-d2-anthropometry-short-form"},
        "local-sleep-t2-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d2-anthropometry-short"},
        "local-sleep-t2-d2-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-d2-cpap-upload",form_module:"local-sleep-t2-d2-cpap-upload-form"},
        "local-sleep-t2-d2-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-d2-cpap-upload"},
        "local-sleep-t2-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d2-cpap",form_module:"local-sleep-t2-d2-cpap-form"},
        "local-sleep-t2-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d2-cpap"},

        "local-sleep-t2-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d3-anthropometry-short",form_module:"local-sleep-t2-d3-anthropometry-short-form"},
        "local-sleep-t2-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d3-anthropometry-short"},
        "local-sleep-t2-d3-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-d3-cpap-upload",form_module:"local-sleep-t2-d3-cpap-upload-form"},
        "local-sleep-t2-d3-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-d3-cpap-upload"},
        "local-sleep-t2-d3-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d3-cpap",form_module:"local-sleep-t2-d3-cpap-form"},
        "local-sleep-t2-d3-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d3-cpap"},

        "local-sleep-t2-d4-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d4-anthropometry-short",form_module:"local-sleep-t2-d4-anthropometry-short-form"},
        "local-sleep-t2-d4-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d4-anthropometry-short"},
        "local-sleep-t2-d4-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-d4-cpap-upload",form_module:"local-sleep-t2-d4-cpap-upload-form"},
        "local-sleep-t2-d4-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-d4-cpap-upload"},
        "local-sleep-t2-d4-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d4-cpap",form_module:"local-sleep-t2-d4-cpap-form"},
        "local-sleep-t2-d4-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d4-cpap"},

        "local-sleep-t2-d4-bla-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-bla-kss",form_module:"local-sleep-t2-d4-bla-kss-form"},
        "local-sleep-t2-d4-bla-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-bl-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d4-bl-pvt",form_module:"local-sleep-t2-d4-bl-pvt-form"},
        "local-sleep-t2-d4-bl-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d4-bl-pvt"},
        "local-sleep-t2-d4-blb-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-blb-kss",form_module:"local-sleep-t2-d4-blb-kss-form"},
        "local-sleep-t2-d4-blb-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t1a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t1a-kss",form_module:"local-sleep-t2-d4-t1a-kss-form"},
        "local-sleep-t2-d4-t1a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t1-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d4-t1-pvt",form_module:"local-sleep-t2-d4-t1-pvt-form"},
        "local-sleep-t2-d4-t1-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d4-t1-pvt"},
        "local-sleep-t2-d4-t1b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t1b-kss",form_module:"local-sleep-t2-d4-t1b-kss-form"},
        "local-sleep-t2-d4-t1b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t2a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t2a-kss",form_module:"local-sleep-t2-d4-t2a-kss-form"},
        "local-sleep-t2-d4-t2a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t2-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d4-t2-pvt",form_module:"local-sleep-t2-d4-t2-pvt-form"},
        "local-sleep-t2-d4-t2-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d4-t2-pvt"},
        "local-sleep-t2-d4-t2b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t2b-kss",form_module:"local-sleep-t2-d4-t2b-kss-form"},
        "local-sleep-t2-d4-t2b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t3a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t3a-kss",form_module:"local-sleep-t2-d4-t3a-kss-form"},
        "local-sleep-t2-d4-t3a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t3-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d4-t3-pvt",form_module:"local-sleep-t2-d4-t3-pvt-form"},
        "local-sleep-t2-d4-t3-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d4-t3-pvt"},
        "local-sleep-t2-d4-t3b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t3b-kss",form_module:"local-sleep-t2-d4-t3b-kss-form"},
        "local-sleep-t2-d4-t3b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d4-t4a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t4a-kss",form_module:"local-sleep-t2-d4-t4a-kss-form"},
        "local-sleep-t2-d4-t4a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d4-t4-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d4-t4-pvt",form_module:"local-sleep-t2-d4-t4-pvt-form"},
        "local-sleep-t2-d4-t4-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d4-t4-pvt",task_name:"KSS After PVT"},
        "local-sleep-t2-d4-t4b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d4-t4b-kss",form_module:"local-sleep-t2-d4-t4b-kss-form"},
        "local-sleep-t2-d4-t4b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d4-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d5-t5a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d5-t5a-kss",form_module:"local-sleep-t2-d5-t5a-kss-form"},
        "local-sleep-t2-d5-t5a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d5-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-t2-d5-t5-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-t2-d5-t5-pvt",form_module:"local-sleep-t2-d5-t5-pvt-form"},
        "local-sleep-t2-d5-t5-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-t2-d5-t5-pvt",task_name:"KSS After PVT"},
        "local-sleep-t2-d5-t5b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-t2-d5-t5b-kss",form_module:"local-sleep-t2-d5-t5b-kss-form"},
        "local-sleep-t2-d5-t5b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-t2-d5-t5b-kss",task_name:"KSS After PVT"},

        "local-sleep-t2-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d1-anthropometry-short",form_module:"local-sleep-t2-d1-anthropometry-short-form"},
        "local-sleep-t2-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d1-anthropometry-short"},
        "local-sleep-t2-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-t2-d1-ess",form_module:"local-sleep-t2-d1-ess-form"},
        "local-sleep-t2-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-t2-d1-ess",task_name:"ESS"},
        "local-sleep-t2-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-t2-d1-dass",form_module:"local-sleep-t2-d1-dass-form"},
        "local-sleep-t2-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-t2-d1-dass",task_name:"DASS"},
        "local-sleep-t2-d1-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-d1-cpap-upload",form_module:"local-sleep-t2-d1-cpap-upload-form"},
        "local-sleep-t2-d1-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-d1-cpap-upload"},
        "local-sleep-t2-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-t2-d1-cpap",form_module:"local-sleep-t2-d1-cpap-form"},
        "local-sleep-t2-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-t2-d1-cpap"},

        "local-sleep-t2-d5-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-t2-d5-anthropometry-short",form_module:"local-sleep-t2-d5-anthropometry-short-form"},
        "local-sleep-t2-d5-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-t2-d5-anthropometry-short"},

        "local-sleep-t2-g1-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-t2-g1-psg300",form_module:"local-sleep-t2-g1-psg300-form"},
        "local-sleep-t2-g1-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-t2-g1-psg300"},
        "local-sleep-t2-g2-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-t2-g2-psg300",form_module:"local-sleep-t2-g2-psg300-form"},
        "local-sleep-t2-g2-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-t2-g2-psg300"},
        "local-sleep-t2-g1-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g1-psgedf",form_module:"local-sleep-t2-g1-psgedf-form"},
        "local-sleep-t2-g1-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g1-psgedf"},
        "local-sleep-t2-g2-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g2-psgedf",form_module:"local-sleep-t2-g2-psgedf-form"},
        "local-sleep-t2-g2-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g2-psgedf"},
        "local-sleep-t2-g1-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g1-sleep-scoring",form_module:"local-sleep-t2-g1-sleep-scoring-form"},
        "local-sleep-t2-g1-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g1-sleep-scoring"},
        "local-sleep-t2-g2-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g2-sleep-scoring",form_module:"local-sleep-t2-g2-sleep-scoring-form"},
        "local-sleep-t2-g2-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g2-sleep-scoring"},
        "local-sleep-t2-g-source-doc-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g-source-doc",form_module:"local-sleep-t2-g-source-doc-form"},
        "local-sleep-t2-g-source-doc-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g-source-doc"},
        "local-sleep-t2-g-sleep-diary-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g-sleep-diary",form_module:"local-sleep-t2-g-sleep-diary-form"},
        "local-sleep-t2-g-sleep-diary-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g-sleep-diary"},
        "local-sleep-t2-g-finapres-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g-finapres",form_module:"local-sleep-t2-g-finapres-form"},
        "local-sleep-t2-g-finapres-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g-finapres"},
        "local-sleep-t2-g-geoscan-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-t2-g-geoscan",form_module:"local-sleep-t2-g-geoscan-form"},
        "local-sleep-t2-g-geoscan-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-t2-g-geoscan"},

        "local-sleep-fu-d1-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d1-anthropometry-short",form_module:"local-sleep-fu-d1-anthropometry-short-form"},
        "local-sleep-fu-d1-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d1-anthropometry-short"},
        "local-sleep-fu-d1-ess-data":		                {url:"$A/modules/ess-data.html",Table:"local-sleep-fu-d1-ess",form_module:"local-sleep-fu-d1-ess-form"},
        "local-sleep-fu-d1-ess-form":		                {url:"$A/modules/ess-form.html",Table:"local-sleep-fu-d1-ess",task_name:"ESS"},
        "local-sleep-fu-d1-dass-data":		                {url:"$A/modules/dass-data.html",Table:"local-sleep-fu-d1-dass",form_module:"local-sleep-fu-d1-dass-form"},
        "local-sleep-fu-d1-dass-form":		                {url:"$A/modules/dass-form.html",Table:"local-sleep-fu-d1-dass",task_name:"DASS"},
        "local-sleep-fu-d1-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-d1-cpap-upload",form_module:"local-sleep-fu-d1-cpap-upload-form"},
        "local-sleep-fu-d1-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-d1-cpap-upload"},
        "local-sleep-fu-d1-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-fu-d1-cpap",form_module:"local-sleep-fu-d1-cpap-form"},
        "local-sleep-fu-d1-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-fu-d1-cpap"},

        "local-sleep-fu-d2-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d2-anthropometry-short",form_module:"local-sleep-fu-d2-anthropometry-short-form"},
        "local-sleep-fu-d2-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d2-anthropometry-short"},
        "local-sleep-fu-d2-cpap-upload-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-d2-cpap-upload",form_module:"local-sleep-fu-d2-cpap-upload-form"},
        "local-sleep-fu-d2-cpap-upload-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-d2-cpap-upload"},
        "local-sleep-fu-d2-cpap-data":		                {url:"$A/modules/cpap-data.html",Table:"local-sleep-fu-d2-cpap",form_module:"local-sleep-fu-d2-cpap-form"},
        "local-sleep-fu-d2-cpap-form":		                {url:"$A/modules/cpap-form.html",Table:"local-sleep-fu-d2-cpap"},

        "local-sleep-fu-d2-bla-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-bla-kss",form_module:"local-sleep-fu-d2-bla-kss-form"},
        "local-sleep-fu-d2-bla-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-bla-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-bl-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d2-bl-pvt",form_module:"local-sleep-fu-d2-bl-pvt-form"},
        "local-sleep-fu-d2-bl-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d2-bl-pvt"},
        "local-sleep-fu-d2-blb-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-blb-kss",form_module:"local-sleep-fu-d2-blb-kss-form"},
        "local-sleep-fu-d2-blb-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-blb-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t1a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t1a-kss",form_module:"local-sleep-fu-d2-t1a-kss-form"},
        "local-sleep-fu-d2-t1a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t1a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t1-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d2-t1-pvt",form_module:"local-sleep-fu-d2-t1-pvt-form"},
        "local-sleep-fu-d2-t1-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d2-t1-pvt"},
        "local-sleep-fu-d2-t1b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t1b-kss",form_module:"local-sleep-fu-d2-t1b-kss-form"},
        "local-sleep-fu-d2-t1b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t1b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t2a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t2a-kss",form_module:"local-sleep-fu-d2-t2a-kss-form"},
        "local-sleep-fu-d2-t2a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t2a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t2-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d2-t2-pvt",form_module:"local-sleep-fu-d2-t2-pvt-form"},
        "local-sleep-fu-d2-t2-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d2-t2-pvt"},
        "local-sleep-fu-d2-t2b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t2b-kss",form_module:"local-sleep-fu-d2-t2b-kss-form"},
        "local-sleep-fu-d2-t2b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t2b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t3a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t3a-kss",form_module:"local-sleep-fu-d2-t3a-kss-form"},
        "local-sleep-fu-d2-t3a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t3a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t3-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d2-t3-pvt",form_module:"local-sleep-fu-d2-t3-pvt-form"},
        "local-sleep-fu-d2-t3-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d2-t3-pvt"},
        "local-sleep-fu-d2-t3b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t3b-kss",form_module:"local-sleep-fu-d2-t3b-kss-form"},
        "local-sleep-fu-d2-t3b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t3b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d2-t4a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t4a-kss",form_module:"local-sleep-fu-d2-t4a-kss-form"},
        "local-sleep-fu-d2-t4a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t4a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d2-t4-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d2-t4-pvt",form_module:"local-sleep-fu-d2-t4-pvt-form"},
        "local-sleep-fu-d2-t4-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d2-t4-pvt"},
        "local-sleep-fu-d2-t4b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d2-t4b-kss",form_module:"local-sleep-fu-d2-t4b-kss-form"},
        "local-sleep-fu-d2-t4b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t4b-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d3-t5a-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d3-t5a-kss",form_module:"local-sleep-fu-d3-t5a-kss-form"},
        "local-sleep-fu-d3-t5a-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d3-t5a-kss",task_name:"KSS Before PVT"},
        "local-sleep-fu-d3-t5-pvt-data":		                {url:"$A/modules/pvt-data.html",Table:"local-sleep-fu-d3-t5-pvt",form_module:"local-sleep-fu-d3-t5-pvt-form"},
        "local-sleep-fu-d3-t5-pvt-form":		                {url:"$A/modules/pvt-form.html",Table:"local-sleep-fu-d3-t5-pvt"},
        "local-sleep-fu-d3-t5b-kss-data":		                {url:"$A/modules/kss-data.html",Table:"local-sleep-fu-d3-t5b-kss",form_module:"local-sleep-fu-d3-t5b-kss-form"},
        "local-sleep-fu-d3-t5b-kss-form":		                {url:"$A/modules/kss-form.html",Table:"local-sleep-fu-d2-t45-kss",task_name:"KSS After PVT"},

        "local-sleep-fu-d3-anthropometry-short-data":		                {url:"$A/modules/anthropometry-short-data.html",Table:"local-sleep-fu-d3-anthropometry-short",form_module:"local-sleep-fu-d3-anthropometry-short-form"},
        "local-sleep-fu-d3-anthropometry-short-form":		                {url:"$A/modules/anthropometry-short-form.html",Table:"local-sleep-fu-d3-anthropometry-short"},
 
        "local-sleep-fu-g1-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-fu-g1-psg300",form_module:"local-sleep-fu-g1-psg300-form"},
        "local-sleep-fu-g1-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-fu-g1-psg300"},
        "local-sleep-fu-g2-psg300-data":		                {url:"$A/modules/psg300-data.html",Table:"local-sleep-fu-g2-psg300",form_module:"local-sleep-fu-g2-psg300-form"},
        "local-sleep-fu-g2-psg300-form":		                {url:"$A/modules/psg300-form.html",Table:"local-sleep-fu-g2-psg300"},
        "local-sleep-fu-g1-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g1-psgedf",form_module:"local-sleep-fu-g1-psgedf-form"},
        "local-sleep-fu-g1-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g1-psgedf"},
        "local-sleep-fu-g2-psgedf-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g2-psgedf",form_module:"local-sleep-fu-g2-psgedf-form"},
        "local-sleep-fu-g2-psgedf-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g2-psgedf"},
        "local-sleep-fu-g1-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g1-sleep-scoring",form_module:"local-sleep-fu-g1-sleep-scoring-form"},
        "local-sleep-fu-g1-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g1-sleep-scoring"},
        "local-sleep-fu-g2-sleep-scoring-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g2-sleep-scoring",form_module:"local-sleep-fu-g2-sleep-scoring-form"},
        "local-sleep-fu-g2-sleep-scoring-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g2-sleep-scoring"},
        "local-sleep-fu-g-source-doc-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g-source-doc",form_module:"local-sleep-fu-g-source-doc-form"},
        "local-sleep-fu-g-source-doc-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g-source-doc"},
        "local-sleep-fu-g-sleep-diary-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g-sleep-diary",form_module:"local-sleep-fu-g-sleep-diary-form"},
        "local-sleep-fu-g-sleep-diary-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g-sleep-diary"},
        "local-sleep-fu-g-finapres-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g-finapres",form_module:"local-sleep-fu-g-finapres-form"},
        "local-sleep-fu-g-finapres-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g-finapres"},
        "local-sleep-fu-g-geoscan-data":		                {url:"$A/modules/upload-file-data.html",Table:"local-sleep-fu-g-geoscan",form_module:"local-sleep-fu-g-geoscan-form"},
        "local-sleep-fu-g-geoscan-form":		                {url:"$A/modules/upload-file-form.html",Table:"local-sleep-fu-g-geoscan"},

        "local-sleep-b-d2-1-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-b-d2-1-aused-90",form_module:"local-sleep-b-d2-1-aused-90-form"},
        "local-sleep-b-d2-1-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-b-d2-1-aused-90"},
        "local-sleep-b-d2-2-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-b-d2-2-aused-90",form_module:"local-sleep-b-d2-2-aused-90-form"},
        "local-sleep-b-d2-2-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-b-d2-2-aused-90"},
        "local-sleep-b-d2-3-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-b-d2-3-aused-90",form_module:"local-sleep-b-d2-3-aused-90-form"},
        "local-sleep-b-d2-3-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-b-d2-3-aused-90"},
        "local-sleep-t1-d4-1-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t1-d4-1-aused-90",form_module:"local-sleep-t1-d4-1-aused-90-form"},
        "local-sleep-t1-d4-1-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t1-d4-1-aused-90"},
        "local-sleep-t1-d4-2-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t1-d4-2-aused-90",form_module:"local-sleep-t1-d4-2-aused-90-form"},
        "local-sleep-t1-d4-2-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t1-d4-2-aused-90"},
        "local-sleep-t1-d4-3-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t1-d4-3-aused-90",form_module:"local-sleep-t1-d4-3-aused-90-form"},
        "local-sleep-t1-d4-3-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t1-d4-3-aused-90"},
        "local-sleep-t2-d4-1-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t2-d4-1-aused-90",form_module:"local-sleep-t2-d4-1-aused-90-form"},
        "local-sleep-t2-d4-1-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t2-d4-1-aused-90"},
        "local-sleep-t2-d4-2-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t2-d4-2-aused-90",form_module:"local-sleep-t2-d4-2-aused-90-form"},
        "local-sleep-t2-d4-2-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t2-d4-2-aused-90"},
        "local-sleep-t2-d4-3-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-t2-d4-3-aused-90",form_module:"local-sleep-t2-d4-3-aused-90-form"},
        "local-sleep-t2-d4-3-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-t2-d4-3-aused-90"},
        "local-sleep-fu-d2-1-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-fu-d2-1-aused-90",form_module:"local-sleep-fu-d2-1-aused-90-form"},
        "local-sleep-fu-d2-1-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-fu-d2-1-aused-90"},
        "local-sleep-fu-d2-2-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-fu-d2-2-aused-90",form_module:"local-sleep-fu-d2-2-aused-90-form"},
        "local-sleep-fu-d2-2-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-fu-d2-2-aused-90"},
        "local-sleep-fu-d2-3-aused-90-data":		                {url:"$A/modules/aused-90-data.html",Table:"local-sleep-fu-d2-3-aused-90",form_module:"local-sleep-fu-d2-3-aused-90-form"},
        "local-sleep-fu-d2-3-aused-90-form":		                {url:"$A/modules/aused-90-form.html",Table:"local-sleep-fu-d2-3-aused-90"},

    }
    for(m in modules){$vm.module_list[m]=modules[m];}
})();
